# Notebook Mode: Exploration Only

Bu notebook **keşif ve analiz** içindir.

Production-grade, tekrar üretilebilir pipeline için script kullan:
- `python scripts/train_ranker_leakage_safe.py`
- `python scripts/export_dashboard_artifacts.py`

Notebook çıktıları dashboard artifact dosyalarını doğrudan üretmek için kullanılmamalıdır.

In [77]:
import sys, mlxtend
print("python:", sys.executable)
print("mlxtend:", mlxtend.__version__)

python: /Users/gizemtotkanli/.pyenv/versions/basket_ai/bin/python
mlxtend: 0.24.0

In [1]:
import sys
print(sys.executable)

/Users/gizemtotkanli/.pyenv/versions/basket_ai/bin/python

# 02 — Recommendation Candidate Models

## Objective
Build interpretable and scalable recommendation candidate generators
based on basket co-occurrence, association rules, and item relationships.

This notebook focuses on **candidate generation**, not final ranking.

## 1. Data Loading & Scope

We reuse the cleaned and structured basket-level datasets generated in the
baseline EDA phase.

**Inputs**
- `basket_items`: item-level transactions per basket
- `baskets`: basket-level aggregated features

This notebook does **not** perform data cleaning.
All inputs are assumed to be validated.

In [2]:
# Project setup
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd() if (Path.cwd() / 'data').exists() else Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "processed"

basket_items = pd.read_parquet(DATA_DIR / "baskets" / "basket_items.parquet")
baskets = pd.read_parquet(DATA_DIR / "baskets" / "baskets.parquet")

In [3]:
import os
os.getcwd()

'/Users/gizemtotkanli/projects/basket_ai/notebooks'

In [4]:
from pathlib import Path
import pandas as pd

# Proje root'unu bul (basket_ai)
PROJECT_ROOT = Path.cwd() if (Path.cwd() / 'data').exists() else Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "data" / "processed"

basket_items = pd.read_parquet(DATA_DIR / "baskets" / "basket_items.parquet")
baskets = pd.read_parquet(DATA_DIR / "baskets" / "baskets.parquet")

print("basket_items shape:", basket_items.shape)
print("baskets shape:", baskets.shape)

basket_items shape: (611107, 13)
baskets shape: (142611, 10)

## 2. Candidate Generation Strategy

We build recommendation candidates using **multiple complementary signals**:

1. Association-rule based candidates (FP-Growth)
2. Basket co-occurrence frequency
3. Category-level generalization
4. Item embedding neighbors (Item2Vec)

Each method produces a **candidate set**, not a final ranking.

Final ranking and business logic will be handled downstream.

### 2.1 Association-Rule Candidates (FP-Growth)

We learn frequent itemsets and association rules from baskets, then generate
**recommendation candidates** from the rule consequents given a user's current basket.

We focus on **candidate generation** (recall), not ranking.

In [5]:
from pathlib import Path
from itertools import combinations
from typing import Iterable

import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd() if (Path.cwd() / 'data').exists() else Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "processed" / "baskets"

basket_items_path = DATA_DIR / "basket_items.parquet"
baskets_path      = DATA_DIR / "baskets.parquet"

basket_items = pd.read_parquet(basket_items_path)
baskets = pd.read_parquet(baskets_path)

print("basket_items:", basket_items.shape, "| baskets:", baskets.shape)
print("DATA_DIR:", DATA_DIR)

basket_items: (611107, 13) | baskets: (142611, 10)
DATA_DIR: /Users/gizemtotkanli/projects/basket_ai/data/processed/baskets

In [6]:
# Amaç: sepetlerden A->B kuralları üretmek ve `rules` DF'ini oluşturmak
# Çıktı kolonları: antecedent, consequent, support, confidence, lift, pair_count, a_count, b_count

MIN_PAIR_COUNT = 10        # A ve B en az kaç sepette birlikte olsun
MIN_CONFIDENCE = 0.05      # confidence eşiği
MIN_LIFT       = 1.05      # lift eşiği (1'den büyük olması bağımsızlıktan daha güçlü)
MAX_ITEMS_PER_BASKET = 50  # büyük sepetlerde kombinasyon patlamasın diye limit

# Sepet -> item list (int, unique)
basket_to_items = (
    basket_items.groupby("basket_id")["itemcode"]
    .apply(lambda s: sorted(set(pd.to_numeric(s, errors="coerce").dropna().astype(int).tolist())))
)

n_baskets = int(basket_to_items.shape[0])
print("Num baskets:", n_baskets)
print("Example basket:", basket_to_items.iloc[0][:10], "...")

# Item frekansları: count(A)
item_counts = basket_to_items.explode().value_counts()
item_counts.name = "a_count"
a_count_map = item_counts.to_dict()

# Pair frekansları: count(A,B)
pair_counter = {}

for items in basket_to_items:
    if len(items) < 2:
        continue

    if len(items) > MAX_ITEMS_PER_BASKET:
        items = items[:MAX_ITEMS_PER_BASKET]

    # unordered pairs say (A<B)
    for a, b in combinations(items, 2):
        pair_counter[(a, b)] = pair_counter.get((a, b), 0) + 1

pairs_df = pd.DataFrame(
    [(a, b, c) for (a, b), c in pair_counter.items()],
    columns=["item_a", "item_b", "pair_count"]
)

print("Pairs raw:", pairs_df.shape)

# min birlikte görülme filtresi
pairs_df = pairs_df[pairs_df["pair_count"] >= MIN_PAIR_COUNT].copy()
print("Pairs after MIN_PAIR_COUNT:", pairs_df.shape)

# support bileşenleri
pairs_df["a_count"] = pairs_df["item_a"].map(a_count_map).astype(float)
pairs_df["b_count"] = pairs_df["item_b"].map(a_count_map).astype(float)

pairs_df["support_ab"] = pairs_df["pair_count"] / float(n_baskets)
pairs_df["support_a"]  = pairs_df["a_count"] / float(n_baskets)
pairs_df["support_b"]  = pairs_df["b_count"] / float(n_baskets)

# A->B
rules_ab = pairs_df[[
    "item_a","item_b","pair_count","a_count","b_count","support_ab","support_a","support_b"
]].copy()

rules_ab = rules_ab.rename(columns={"item_a":"antecedent","item_b":"consequent"})
rules_ab["confidence"] = rules_ab["pair_count"] / rules_ab["a_count"].replace(0, np.nan)
rules_ab["lift"]       = rules_ab["confidence"] / rules_ab["support_b"].replace(0, np.nan)

# B->A
rules_ba = pairs_df[[
    "item_a","item_b","pair_count","a_count","b_count","support_ab","support_a","support_b"
]].copy()

rules_ba = rules_ba.rename(columns={"item_b":"antecedent","item_a":"consequent"})
rules_ba["confidence"] = rules_ba["pair_count"] / rules_ba["b_count"].replace(0, np.nan)
rules_ba["lift"]       = rules_ba["confidence"] / rules_ba["support_a"].replace(0, np.nan)

rules = pd.concat([rules_ab, rules_ba], ignore_index=True)
rules = rules.rename(columns={"support_ab":"support"})

rules = rules[[
    "antecedent","consequent",
    "support","confidence","lift",
    "pair_count","a_count","b_count"
]].copy()

# son filtreler
rules = rules.replace([np.inf, -np.inf], np.nan).dropna(subset=["confidence","lift"])
rules = rules[(rules["confidence"] >= MIN_CONFIDENCE) & (rules["lift"] >= MIN_LIFT)].copy()

# sıralama
rules = rules.sort_values(["lift","confidence","pair_count"], ascending=False).reset_index(drop=True)

print("✅ rules created:", rules.shape)
display(rules.head(10))

# (ÖNERİ) rules'u diske kaydet: artık bir daha "rules yok" dramı yaşamazsın
rules_path = DATA_DIR / "rules.parquet"
rules.to_parquet(rules_path, index=False)
print("💾 saved:", rules_path)

Num baskets: 142611
Example basket: [8, 1454, 6372, 8583, 8639, 13519, 20868] ...
Pairs raw: (1226072, 3)
Pairs after MIN_PAIR_COUNT: (23995, 3)
✅ rules created: (12732, 8)

,antecedent,consequent,support,confidence,lift,pair_count,a_count,b_count
0,2059,2060,0.000077,0.392857,1600.735714,11,28.0,35.0
1,2060,2059,0.000077,0.314286,1600.735714,11,28.0,35.0
2,1045,1044,0.000098,0.378378,1587.085851,14,34.0,37.0
3,1044,1045,0.000098,0.411765,1587.085851,14,34.0,37.0
4,4772,4770,0.000077,0.379310,1545.537931,11,35.0,29.0
5,4770,4772,0.000077,0.314286,1545.537931,11,35.0,29.0
6,7816,7819,0.000105,0.517241,1505.394089,15,29.0,49.0
7,7819,7816,0.000105,0.306122,1505.394089,15,29.0,49.0
8,17243,17244,0.000126,0.461538,1400.435352,18,39.0,47.0
9,17244,17243,0.000126,0.382979,1400.435352,18,39.0,47.0

💾 saved: /Users/gizemtotkanli/projects/basket_ai/data/processed/baskets/rules.parquet

In [7]:
def generate_candidates_from_rules(
    basket_itemcodes: Iterable,
    rules: pd.DataFrame,
    top_k: int = 30,
    min_lift: float = 1.2,
    min_confidence: float = 0.0,
) -> pd.DataFrame:
    """
    Basket içindeki ürünleri antecedent olarak alıp rules DF'inden consequent adayları çeker.

    Beklenen rules kolonları (en az):
      - antecedent, consequent, lift
    Opsiyonel:
      - confidence, support

    Çıktı:
      - candidate, score, source
    """
    import pandas as pd
    import numpy as np

    if rules is None or len(rules) == 0:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    basket_set = set(pd.to_numeric(list(basket_itemcodes), errors="coerce"))
    basket_set = {int(x) for x in basket_set if not pd.isna(x)}

    r = rules.copy()

    needed = {"antecedent", "consequent", "lift"}
    missing = needed - set(r.columns)
    if missing:
        raise ValueError(f"rules df missing columns: {missing}. cols={list(r.columns)}")

    mask = r["antecedent"].isin(basket_set) & (r["lift"] >= float(min_lift))
    if "confidence" in r.columns:
        mask = mask & (r["confidence"] >= float(min_confidence))

    cols = ["consequent", "lift"] + (["confidence"] if "confidence" in r.columns else [])
    cand = r.loc[mask, cols].copy()
    if cand.empty:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    cand = cand.rename(columns={"consequent": "candidate", "lift": "score"})

    # sepet içindeki ürünleri adaydan çıkar
    cand = cand[~cand["candidate"].isin(basket_set)].copy()

    # aynı aday birden fazla antecedent'ten gelebilir -> max score al
    cand = (
        cand.groupby("candidate", as_index=False)["score"].max()
            .sort_values("score", ascending=False)
            .head(top_k)
            .reset_index(drop=True)
    )
    cand["source"] = "rules"
    return cand


# quick sanity check
_example_items = basket_to_items.iloc[0]
_rules_cand = generate_candidates_from_rules(_example_items, rules, top_k=10, min_lift=1.2)
print("rules candidates:", _rules_cand.shape)
display(_rules_cand.head(10))

rules candidates: (10, 3)

   candidate      score source
0      20872  21.274883  rules
1      20689  17.106477  rules
2      20883  16.901281  rules
3      20869  15.898662  rules
4      20884  14.598638  rules
5      20871  14.157548  rules
6      20851  13.527809  rules
7         40  12.630760  rules
8      20885  11.230473  rules
9      16413   9.976043  rules

### 2.2 Basket Co-occurrence Candidates

This method generates recommendation candidates based on **pairwise item co-occurrence**
within the same basket.

Unlike association rules:
- No directional implication
- No confidence metric
- Pure frequency-based signal

This signal is especially useful for:
- Short baskets
- Cold-start items
- High-frequency complementary products

In [8]:
import pandas as pd
import numpy as np
from typing import Iterable, List

In [9]:
def clean_itemcodes(itemcodes: Iterable) -> List[int]:
    """
    Basket içindeki itemcode listesini temizler:
    - NaN / None atar
    - float gelenleri int'e çevirir (örn 5715.0 -> 5715)
    - tekrarı kaldırır
    """
    s = pd.Series(list(itemcodes), dtype="float64").dropna()
    if s.empty:
        return []
    s = s.astype("int64")
    return s.drop_duplicates().tolist()

In [10]:
basket_to_items = (
    basket_items.groupby("basket_id")["itemcode"]
    .apply(clean_itemcodes)  # NaN-safe + int'e çeviriyor
)

print("Num baskets:", basket_to_items.shape[0])
print("Example basket:", basket_to_items.iloc[0])

Num baskets: 142611
Example basket: [8, 1454, 6372, 8583, 8639, 13519, 20868]

In [11]:
from itertools import combinations
from collections import Counter

pair_counter = Counter()

for items in basket_to_items:
    if len(items) < 2:
        continue
    for a, b in combinations(items, 2):
        pair_counter[(a, b)] += 1
        pair_counter[(b, a)] += 1  # simetrik

cooc_df = (
    pd.DataFrame(
        [(a, b, c) for (a, b), c in pair_counter.items()],
        columns=["item_a", "item_b", "cooc_count"],
    )
    .sort_values("cooc_count", ascending=False)
    .reset_index(drop=True)
)

print("Co-occurrence rows:", cooc_df.shape)
cooc_df.head(10)

Co-occurrence rows: (2503514, 3)

   item_a  item_b  cooc_count
0    5716    5715        1447
1    5715    5716        1447
2    5461    5518        1007
3    5518    5461        1007
4    5707    5694         912
5    5694    5707         912
6    5461    6261         886
7    6261    5461         886
8   20885       8         880
9       8   20885         880

In [12]:
def generate_candidates_from_cooc(
    basket_itemcodes: Iterable,
    cooc_df: pd.DataFrame,
    top_k: int = 20,
    min_count: int = 5
) -> pd.DataFrame:
    """
    Basket co-occurrence tablosundan aday üretir.
    Output: candidate + score(cooc_count) + source
    """
    # 1) basket temizle (NaN-safe)
    basket_itemcodes = clean_itemcodes(basket_itemcodes)
    basket_set = set(basket_itemcodes)

    if len(basket_set) == 0:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    # 2) cooc_df temizle (NaN-safe)
    df = cooc_df.dropna(subset=["item_a", "item_b", "cooc_count"]).copy()

    # 3) filtre: basket item'larından dışarı giden kenarlar
    filt = (
        df["item_a"].isin(basket_set) &
        (~df["item_b"].isin(basket_set)) &
        (df["cooc_count"] >= min_count)
    )

    cand = df.loc[filt, ["item_b", "cooc_count"]].copy()
    if cand.empty:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    # 4) aday bazında skorları topla (aynı candidate farklı item_a'dan gelebilir)
    cand = (
        cand.rename(columns={"item_b": "candidate", "cooc_count": "score"})
            .groupby("candidate", as_index=False)["score"].sum()
            .sort_values("score", ascending=False)
            .head(top_k)
            .reset_index(drop=True)
    )

    # 5) tipleri stabilize et + source ekle
    cand["candidate"] = cand["candidate"].astype(int)
    cand["score"] = cand["score"].astype(float)
    cand["source"] = "cooc"

    return cand

In [13]:
example_basket_id = baskets["basket_id"].iloc[0]
example_items = basket_items.loc[
    basket_items["basket_id"] == example_basket_id, "itemcode"
].tolist()

print("Example basket id:", example_basket_id)
print("Example basket size:", len(example_items))
print("Example items:", example_items)

generate_candidates_from_cooc(example_items, cooc_df, top_k=10, min_count=5)

Example basket id: 15560
Example basket size: 7
Example items: [8.0, 1454.0, 6372.0, 8583.0, 8639.0, 13519.0, 20868.0]

   candidate   score source
0      20885  1489.0   cooc
1      20869   908.0   cooc
2       5715   671.0   cooc
3      20884   636.0   cooc
4       5716   572.0   cooc
5       5694   563.0   cooc
6      20872   554.0   cooc
7      14745   524.0   cooc
8       3190   453.0   cooc
9      20851   447.0   cooc

#### Interpretation & Insights (Basket Co-occurrence)

The co-occurrence matrix captures how frequently two items appear together across all baskets.

Key observations:
- The dataset yields millions of co-occurrence pairs, indicating rich and dense basket interactions.
- Top co-occurring item pairs typically represent:
  - Complementary products
  - Strong substitutes
  - Brand or category bundles
- Unlike association rules, co-occurrence does not require strict confidence thresholds and therefore provides higher recall.

Why this matters:
- Co-occurrence candidates are robust for short baskets and sparse user signals.
- This method complements FP-Growth by recovering popular and intuitive recommendations that rules may miss.

In the recommendation system, co-occurrence candidates act as a **high-recall signal**, later combined with other candidate sources.

### 2.3 Category-level Generalization

Category-level candidate generation addresses sparsity and cold-start scenarios by generalizing item interactions to higher-level product categories.

Instead of relying solely on exact item co-occurrences or rules, we leverage category information to recommend alternative or complementary items within the same category.

This approach:
- Improves recall for rare and long-tail items
- Enables recommendations when item-level signals are weak
- Provides robustness against catalog churn

Category-based candidates are especially useful as a fallback signal and are combined with item-level candidates downstream.

In [14]:
# 2.3 prerequisites check
required_cols = {"basket_id", "itemcode", "CATEGORY_NAME2"}
missing = required_cols - set(basket_items.columns)

print("basket_items shape:", basket_items.shape)
print("missing cols:", missing)
assert not missing, f"basket_items içinde eksik kolon(lar) var: {missing}"

basket_items shape: (611107, 13)
missing cols: set()

In [15]:
# Build item -> category mapping
item_to_category = (
    basket_items[["itemcode", "CATEGORY_NAME2"]]
    .dropna(subset=["itemcode", "CATEGORY_NAME2"])
    .drop_duplicates()
    .set_index("itemcode")["CATEGORY_NAME2"]
)

print("Unique items:", item_to_category.shape[0])
print("Unique categories:", item_to_category.nunique())
print("item_to_category index name:", item_to_category.index.name)
print("item_to_category name:", item_to_category.name)

Unique items: 9082
Unique categories: 63
item_to_category index name: itemcode
item_to_category name: CATEGORY_NAME2

In [16]:
# Category -> items list (candidate pool per category)
category_to_items = (
    item_to_category
    .reset_index()
    .groupby("CATEGORY_NAME2")["itemcode"]
    .apply(lambda s: sorted(set(s.astype(int))))
)

# Category popularity proxy (how many unique items exist in that category)
category_pop = category_to_items.apply(len)

print("category_to_items:", category_to_items.shape)
print("Top categories by size:")
display(category_pop.sort_values(ascending=False).head(10))

category_to_items: (63,)
Top categories by size:

CATEGORY_NAME2
MUTFAK EŞYA GEREÇLERİ    675
SAÇ BAKIM                650
BÜSKİVİ ÇEREZ            623
EV TEMİZLEYİCİ           434
ÇAY KAHVE                428
HAZIR YEMEKLER           398
ÇAMAŞIR YIKAMA           350
DUŞ BANYO                349
KAHVALTILIK              318
GAZSIZ İÇECEK            264
Name: itemcode, dtype: int64

In [17]:
import numpy as np
import pandas as pd
from typing import Iterable

def _clean_itemcodes(itemcodes: Iterable) -> list[int]:
    """
    NaN/None atar, float->int yapar, tekrarları kaldırır.
    """
    s = pd.Series(list(itemcodes), dtype="float64").dropna()
    if s.empty:
        return []
    return s.astype("int64").drop_duplicates().tolist()

def generate_candidates_from_categories(
    basket_itemcodes: Iterable,
    item_to_category: pd.Series,
    category_to_items: pd.Series,
    category_pop: pd.Series,
    top_k: int = 20
) -> pd.DataFrame:
    """
    Category-level generalization candidates.
    Output columns (stable + blend-ready):
      - candidate (int)
      - score (float)  -> category size proxy
      - source (str)   -> "category"
      - category (str) -> debug/info
    """
    EMPTY = pd.DataFrame(columns=["candidate", "score", "source", "category"])

    basket_itemcodes = _clean_itemcodes(basket_itemcodes)
    basket_set = set(basket_itemcodes)
    if not basket_set:
        return EMPTY

    # Basket'teki kategorileri bul
    basket_categories = set()
    for it in basket_set:
        cat = item_to_category.get(it, None)
        if pd.notna(cat) and cat is not None:
            basket_categories.add(cat)

    if not basket_categories:
        return EMPTY

    # Bu kategorilerdeki tüm item'lar candidate havuzu
    out_rows = []
    for cat in basket_categories:
        items_in_cat = category_to_items.get(cat, [])
        if not items_in_cat:
            continue

        # Sepette zaten olanları önerme
        for cand in items_in_cat:
            if cand not in basket_set:
                out_rows.append((cand, float(category_pop.get(cat, 0)), "category", cat))

    if not out_rows:
        return EMPTY

    cand = pd.DataFrame(out_rows, columns=["candidate", "score", "source", "category"])

    # Aynı candidate birden fazla kategoriye düşerse en yüksek score'u tut (çok nadir ama güvenli)
    cand = (
        cand.sort_values(["score"], ascending=False)
            .groupby("candidate", as_index=False)
            .agg(score=("score", "max"), source=("source", "first"), category=("category", "first"))
            .sort_values(["score", "candidate"], ascending=[False, True])
            .head(top_k)
            .reset_index(drop=True)
    )

    cand["candidate"] = cand["candidate"].astype(int)
    cand["score"] = cand["score"].astype(float)
    cand["source"] = "category"
    return cand

In [18]:
# Example basket items
example_basket_id = baskets["basket_id"].iloc[0]
example_items = basket_items.loc[
    basket_items["basket_id"] == example_basket_id,
    "itemcode"
].tolist()

print("Example basket id:", example_basket_id)
print("Example basket size:", len(example_items))
print("Example items:", example_items[:10], "...")

cat_cand = generate_candidates_from_categories(
    example_items,
    item_to_category=item_to_category,
    category_to_items=category_to_items,
    category_pop=category_pop,
    top_k=15
)

cat_cand

Example basket id: 15560
Example basket size: 7
Example items: [8.0, 1454.0, 6372.0, 8583.0, 8639.0, 13519.0, 20868.0] ...

    candidate  score    source   category
0          16  428.0  category  ÇAY KAHVE
1          77  428.0  category  ÇAY KAHVE
2          81  428.0  category  ÇAY KAHVE
3         267  428.0  category  ÇAY KAHVE
4         268  428.0  category  ÇAY KAHVE
5         283  428.0  category  ÇAY KAHVE
6         294  428.0  category  ÇAY KAHVE
7         307  428.0  category  ÇAY KAHVE
8         319  428.0  category  ÇAY KAHVE
9         331  428.0  category  ÇAY KAHVE
10        343  428.0  category  ÇAY KAHVE
11        348  428.0  category  ÇAY KAHVE
12        364  428.0  category  ÇAY KAHVE
13        365  428.0  category  ÇAY KAHVE
14        366  428.0  category  ÇAY KAHVE

In [19]:
print("item_to_category exists?", "item_to_category" in globals())
print("item_to_category head:")
item_to_category.head()

item_to_category exists? True
item_to_category head:

itemcode
8.0            ÇAY KAHVE
1454.0           MAKARNA
6372.0            PEYNİR
8583.0    ÇAMAŞIR YIKAMA
8639.0    ÇAMAŞIR YIKAMA
Name: CATEGORY_NAME2, dtype: object

In [20]:
# category -> unique item list
tmp = (
    basket_items[["itemcode", "CATEGORY_NAME2"]]
    .dropna()
    .drop_duplicates()
)

category_to_items = (
    tmp.groupby("CATEGORY_NAME2")["itemcode"]
    .apply(lambda s: sorted(set(s.astype(int))))
    .to_dict()
)

print("n_categories:", len(category_to_items))
print("example category:", next(iter(category_to_items.keys())))
print("n_items in example category:", len(category_to_items[next(iter(category_to_items.keys()))]))

n_categories: 63
example category: AĞIZ BAKIM
n_items in example category: 259

In [21]:
# category popularity = how many rows (item occurrences) in basket_items for that category
category_pop = (
    basket_items["CATEGORY_NAME2"]
    .dropna()
    .value_counts()
    .to_dict()
)

print("category_pop example:", list(category_pop.items())[:5])

category_pop example: [('BÜSKİVİ ÇEREZ', 77218), ('SEBZE', 65666), ('ÇİKOLATA GOFRET', 32113), ('ÇAY KAHVE', 31465), ('UNLU MAMÜLLER', 29053)]

**Notes on Category-level Candidates**

Category-based candidate generation acts as a high-recall fallback signal.

Since all candidates originate from the same category, scores are uniform by design and do not represent personalized ranking.  
This signal is primarily used to:
- mitigate cold-start scenarios
- cover long-tail items
- provide robustness when item-level signals are sparse

Final ranking is performed downstream by combining this signal with item-level and embedding-based candidates.

### 2.4 Item Embedding Neighbors (Item2Vec)

We use product-item embeddings trained on basket sequences (Item2Vec-style) to retrieve semantically similar items.

This method is:
- scalable (precomputed nearest neighbors)
- strong for "substitutes" (similar products) and some complements
- robust against sparsity compared to pure co-occurrence counts

We treat embedding neighbors as a candidate generator (recall), not a final ranker.
Downstream ranking can combine this signal with rules/co-occurrence/category candidates.

In [22]:
import pandas as pd
from typing import Iterable

if "clean_itemcodes" not in globals():
    from typing import List

    def clean_itemcodes(itemcodes: Iterable) -> List[int]:
        """
        Basket içindeki itemcode listesini temizler:
        - NaN / None atar
        - float gelenleri int'e çevirir (örn 5715.0 -> 5715)
        - tekrarları kaldırır
        """
        s = pd.Series(list(itemcodes), dtype="float64").dropna().astype("int64")
        return s.drop_duplicates().tolist()

In [23]:
from pathlib import Path

PROJECT_ROOT = Path.cwd() if (Path.cwd() / 'data').exists() else Path.cwd().parent
GEN_DIR = PROJECT_ROOT / "data" / "generated" / "embeddings"

neighbors_path = GEN_DIR / "product_neighbors_top20.csv"
neighbors = pd.read_csv(neighbors_path)

print("neighbors shape:", neighbors.shape)
print("columns:", list(neighbors.columns))
neighbors.head()

neighbors shape: (10000, 3)
columns: ['itemcode', 'neighbor_itemcode', 'similarity']

   itemcode  neighbor_itemcode  similarity
0         7               6219    0.760796
1         7               2108    0.758208
2         7              12228    0.757209
3         7              16597    0.745960
4         7              11756    0.722782

In [24]:
def generate_candidates_from_embeddings(
    basket_itemcodes: Iterable,
    neighbors_df: pd.DataFrame,
    top_k: int = 20,
    min_similarity: float = 0.0
) -> pd.DataFrame:
    """
    Item2Vec/embedding komşuları ile aday üretir.
    Output schema: [candidate, score, source]
      - candidate: öneri itemcode
      - score: similarity
      - source: "embedding"
    """
    basket_itemcodes = clean_itemcodes(basket_itemcodes)
    basket_set = set(basket_itemcodes)

    if len(basket_set) == 0:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    # gerekli kolonlar var mı?
    needed = {"itemcode", "neighbor_itemcode", "similarity"}
    missing = needed - set(neighbors_df.columns)
    if missing:
        raise ValueError(f"neighbors_df missing columns: {missing}")

    # sepetteki item'ların komşularını al, sepette olanları çıkar, similarity filtresi uygula
    cand = neighbors_df[
        (neighbors_df["itemcode"].isin(basket_set)) &
        (~neighbors_df["neighbor_itemcode"].isin(basket_set)) &
        (neighbors_df["similarity"] >= min_similarity)
    ].copy()

    if cand.empty:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    # normalize schema
    cand = (
        cand[["neighbor_itemcode", "similarity"]]
        .rename(columns={"neighbor_itemcode": "candidate", "similarity": "score"})
        .sort_values("score", ascending=False)
        .head(top_k)
        .reset_index(drop=True)
    )

    # tipleri sabitle + source ekle
    cand["candidate"] = cand["candidate"].astype(int)
    cand["score"] = cand["score"].astype(float)
    cand["source"] = "embedding"
    return cand

In [25]:
example_basket_id = baskets["basket_id"].iloc[0]
example_items = basket_items.loc[
    basket_items["basket_id"] == example_basket_id,
    "itemcode"
].tolist()

print("Example basket id:", example_basket_id)
print("Example basket size:", len(example_items))
print("Example items:", example_items)

emb_cand = generate_candidates_from_embeddings(
    example_items,
    neighbors,
    top_k=15,
    min_similarity=0.6
)
emb_cand

Example basket id: 15560
Example basket size: 7
Example items: [8.0, 1454.0, 6372.0, 8583.0, 8639.0, 13519.0, 20868.0]

    candidate     score     source
0         723  0.799046  embedding
1        1318  0.795077  embedding
2        2539  0.782969  embedding
3       20885  0.781366  embedding
4       23509  0.775738  embedding
5        5796  0.767042  embedding
6       20869  0.761489  embedding
7       10992  0.741000  embedding
8        4827  0.736008  embedding
9       20879  0.735465  embedding
10      14500  0.730223  embedding
11       8245  0.729340  embedding
12       3234  0.728069  embedding
13      20871  0.728043  embedding
14        846  0.725596  embedding

In [26]:
print("Neighbor table OK:", neighbors.shape, "cols:", list(neighbors.columns))
print("Unique sources in output:", emb_cand["source"].unique() if not emb_cand.empty else "EMPTY")

Neighbor table OK: (10000, 3) cols: ['itemcode', 'neighbor_itemcode', 'similarity']
Unique sources in output: ['embedding']

### 2.5 Candidate Union (Multi-signal)

Each generator returns a candidate list with its own scoring semantics.
We unify all candidates into a single table with a common schema:

- candidate (itemcode)
- score (method-specific proxy)
- source (rules / cooc / category / embedding)

Then we:
1) concatenate all sources
2) remove candidates already in the basket
3) aggregate duplicates (same candidate from multiple sources)
4) keep per-source scores (optional) and compute a final blended score proxy

This produces the final candidate pool for downstream ranking.

In [27]:
# 2.5 - Hücre 1: Imports

import numpy as np
import pandas as pd
from typing import Optional, Dict, Iterable

In [28]:
# 2.5 - Hücre 2: (Opsiyonel) Mini kontrol
# Bu isimler önceki bölümlerde tanımlı mı? (Hata verirse, eksik olanı önceki bölümlerden geri getiririz.)

required = [
    "baskets", "basket_items", "rules", "cooc_df", "item_to_category", "neighbors",
    "generate_candidates_from_rules",
    "generate_candidates_from_cooc",
    "generate_candidates_from_categories",
    "generate_candidates_from_embeddings",
]
missing = [x for x in required if x not in globals()]
print("Missing:", missing)

Missing: []

In [29]:
# 2.5 - Hücre 3: Aday DF'lerini standardize eden yardımcı

def _ensure_candidate_schema(df: Optional[pd.DataFrame], source: str) -> pd.DataFrame:
    """
    Standardize a candidate df into columns: candidate, score, source
    - candidate: int
    - score: float
    - source: str
    """
    if df is None or len(df) == 0:
        return pd.DataFrame(columns=["candidate", "score", "source"])

    out = df.copy()

    # candidate column
    if "candidate" not in out.columns:
        # allow alt naming
        for c in ["neighbor_itemcode", "item_b", "itemcode_b", "item"]:
            if c in out.columns:
                out = out.rename(columns={c: "candidate"})
                break

    # score column
    if "score" not in out.columns:
        for c in ["similarity", "cooc_count", "confidence", "lift", "weighted_score", "blended_score"]:
            if c in out.columns:
                out = out.rename(columns={c: "score"})
                break

    if "candidate" not in out.columns:
        raise ValueError(f"[{source}] candidate column not found. cols={list(df.columns)}")

    if "score" not in out.columns:
        # worst case: constant score
        out["score"] = 1.0

    out["source"] = source
    out = out[["candidate", "score", "source"]].copy()

    # normalize dtypes (itemcodes sometimes float from parquet)
    out["candidate"] = pd.to_numeric(out["candidate"], errors="coerce")
    out = out.dropna(subset=["candidate"])
    out["candidate"] = out["candidate"].astype(int)

    out["score"] = pd.to_numeric(out["score"], errors="coerce").fillna(0.0).astype(float)
    return out

In [30]:
# 2.5 - Hücre 4: Multi-signal union / blending

def union_candidates(
    basket_itemcodes: Iterable,
    rules_df: Optional[pd.DataFrame] = None,
    cooc_df_in: Optional[pd.DataFrame] = None,
    cat_df: Optional[pd.DataFrame] = None,
    emb_df: Optional[pd.DataFrame] = None,
    top_k: int = 200,
    weights: Optional[Dict[str, float]] = None,
) -> pd.DataFrame:
    """
    Merge candidates from multiple generators and output a unified pool.

    Output schema:
      candidate (int), blended_score (float), n_sources (int), sources (str)
    """

    basket_set = set(pd.to_numeric(list(basket_itemcodes), errors="coerce"))
    basket_set = {int(x) for x in basket_set if not pd.isna(x)}

    # Default heuristic weights (you can tune)
    if weights is None:
        weights = {
            "rules": 1.00,
            "embedding": 0.90,
            "cooc": 0.75,
            "category": 0.40,
        }

    parts = [
        _ensure_candidate_schema(rules_df, "rules"),
        _ensure_candidate_schema(cooc_df_in, "cooc"),
        _ensure_candidate_schema(cat_df, "category"),
        _ensure_candidate_schema(emb_df, "embedding"),
    ]

    all_cand = pd.concat(parts, ignore_index=True)

    # remove already-in-basket
    all_cand = all_cand[~all_cand["candidate"].isin(basket_set)].copy()

    if all_cand.empty:
        return pd.DataFrame(columns=["candidate", "blended_score", "n_sources", "sources"])

    # per-source min-max normalization (robust)
    all_cand["score_norm"] = 0.0
    for src, g in all_cand.groupby("source"):
        s = g["score"].astype(float)
        lo, hi = float(s.min()), float(s.max())
        if hi > lo:
            all_cand.loc[g.index, "score_norm"] = (s - lo) / (hi - lo)
        else:
            all_cand.loc[g.index, "score_norm"] = 0.0

    # apply source weights
    all_cand["w"] = all_cand["source"].map(weights).fillna(0.5).astype(float)
    all_cand["weighted"] = all_cand["score_norm"] * all_cand["w"]

    # aggregate: sum weighted evidence across sources; count sources
    agg = (
        all_cand
        .groupby("candidate", as_index=False)
        .agg(
            blended_score=("weighted", "sum"),
            n_sources=("source", "nunique"),
        )
        .sort_values(["blended_score", "n_sources"], ascending=False)
    )

    # keep which sources supported each candidate (nice for debugging)
    src_list = (
        all_cand
        .groupby("candidate")["source"]
        .apply(lambda x: ",".join(sorted(set(x))))
        .rename("sources")
        .reset_index()
    )

    out = agg.merge(src_list, on="candidate", how="left")
    out = out.head(top_k).reset_index(drop=True)
    return out

In [31]:
# 2.5 - Example basket + her kaynaktan aday üret + union

example_basket_id = baskets["basket_id"].iloc[0]
example_items = basket_items.loc[
    basket_items["basket_id"] == example_basket_id, "itemcode"
].tolist()

print("Example basket_id:", example_basket_id)
print("Example basket size:", len(example_items))
print("Example items:", example_items)

rules_cand = generate_candidates_from_rules(example_items, rules, top_k=30, min_lift=1.2)
cooc_cand  = generate_candidates_from_cooc(example_items, cooc_df, top_k=30, min_count=5)

cat_cand = generate_candidates_from_categories(
    basket_itemcodes=example_items,
    item_to_category=item_to_category,
    category_to_items=category_to_items,
    category_pop=category_pop,
    top_k=30
)

emb_cand  = generate_candidates_from_embeddings(example_items, neighbors, top_k=30, min_similarity=0.6)

final_pool = union_candidates(
    example_items,
    rules_df=rules_cand,
    cooc_df_in=cooc_cand,   # kritik: sende bu isim
    cat_df=cat_cand,
    emb_df=emb_cand,
    top_k=50
)

final_pool.head(20)

Example basket_id: 15560
Example basket size: 7
Example items: [8.0, 1454.0, 6372.0, 8583.0, 8639.0, 13519.0, 20868.0]

    candidate  blended_score  n_sources               sources
0       20885       1.960052          3  cooc,embedding,rules
1       20869       1.661992          3  cooc,embedding,rules
2       20872       1.177083          2            cooc,rules
3       20884       0.983582          3  cooc,embedding,rules
4       20871       0.932921          3  cooc,embedding,rules
5         723       0.900000          1             embedding
6        1318       0.862888          1             embedding
7       20689       0.782284          1                 rules
8       20883       0.771566          1                 rules
9        2539       0.749657          1             embedding
10      20851       0.706889          2            cooc,rules
11      23509       0.682037          1             embedding
12       5796       0.600719          1             embedding
13         40       0.548516          1                 rules
14      16413       0.473585          2            cooc,rules
15      20867       0.454897          2            cooc,rules
16      14745       0.441666          2            cooc,rules
17       3159       0.360396          1                 rules
18      10992       0.357198          1             embedding
19       4827       0.310516          1             embedding

In [32]:
print("rules:", rules_cand.shape)
print("cooc :", cooc_cand.shape)
print("cat  :", cat_cand.shape)
print("emb  :", emb_cand.shape)

rules: (30, 3)
cooc : (30, 3)
cat  : (30, 4)
emb  : (30, 3)

We now proceed to offline evaluation and ranking considerations based on this candidate pool.

## 2.5 Candidate Pool — Results & Interpretation

At this stage, we have successfully constructed a **multi-signal candidate generation pipeline** that combines heterogeneous recommendation signals into a single, explainable candidate pool.

### What this table represents

Each row corresponds to a **candidate item** that may be recommended given a user basket.  
The candidates are generated using **multiple independent methods**, then merged and scored jointly.

**Columns:**

- **candidate**  
  Item identifier proposed for recommendation.

- **blended_score**  
  A normalized and aggregated score derived from multiple signals (association rules, co-occurrence, embeddings, category generalization).

- **n_sources**  
  Number of independent candidate generators that produced this item.  
  This acts as a strong confidence proxy.

- **sources**  
  Explicit list of methods that contributed this candidate, enabling transparency and interpretability.

---

### Key observations

- Items appearing in **multiple sources (n_sources ≥ 2)** consistently rank at the top.  
  These candidates benefit from *consensus across behavioral, semantic, and structural signals*.

- **Embedding-only candidates** expand the recommendation space toward discovery and long-tail items, improving diversity.

- **Co-occurrence and rule-based candidates** reinforce short-term intent and frequent purchase patterns.

- The resulting candidate pool balances:
  - exploitation (high-confidence items)
  - exploration (novel but relevant items)

---

### Why this matters

This step intentionally **does not perform final ranking**.

Instead, it produces a **high-recall, explainable candidate set**, which is the correct architectural design for production-grade recommender systems.

Final ranking, personalization, and business constraints will be applied downstream using supervised or learning-to-rank models.

---

### Outcome

We now have a robust and extensible candidate generation layer that:
- separates signal generation from ranking logic
- supports explainability and diagnostics
- scales to additional signals without refactoring

This completes the **Candidate Generation phase**.

## 2.6 Candidate Pool Diagnostics

In [33]:
# ============================================================
# 2.6 Candidate Pool Diagnostics
# ============================================================
# Amaç:
# - 2.1 (rules), 2.2 (cooc), 2.3 (category), 2.4 (embedding) kaynaklarından
#   üretilen adayların 2.5'te birleştirilmesi sonrası havuzun sağlığını ölçmek.
# - Örnek bir sepet için "final_pool" çıktısını incelemek
# - Rastgele sepet örnekleminde:
#     * sepet boyutu -> aday sayısı ilişkisi
#     * boş havuz oranı
#     * tek kaynak ağırlığı (n_sources düşük) gibi kırmızı bayrakları görmek
#
# Not:
# - Bu bölüm, 2.1–2.5'te aşağıdaki fonksiyon/objelerin zaten tanımlı olduğunu varsayar:
#   * rules (rules DF) + generate_candidates_from_rules
#   * cooc_df + generate_candidates_from_cooc
#   * item_to_category, category_to_items, category_pop + generate_candidates_from_categories
#   * neighbors + generate_candidates_from_embeddings
#   * union_candidates
# ============================================================

from pathlib import Path
import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd() if (Path.cwd() / 'data').exists() else Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "processed" / "baskets"

basket_items = pd.read_parquet(DATA_DIR / "basket_items.parquet")
baskets = pd.read_parquet(DATA_DIR / "baskets.parquet")

print("basket_items:", basket_items.shape)
print("baskets:", baskets.shape)

basket_items: (611107, 13)
baskets: (142611, 10)

In [34]:
# ------------------------------------------------------------
# Sepet -> item list (int, unique) hazırlığı
# ------------------------------------------------------------
basket_to_items = (
    basket_items.groupby("basket_id")["itemcode"]
    .apply(lambda s: sorted(set(pd.to_numeric(s, errors="coerce").dropna().astype(int).tolist())))
)

print("Num baskets:", basket_to_items.shape[0])
print("Example basket:", basket_to_items.iloc[0][:10], "...")

Num baskets: 142611
Example basket: [8, 1454, 6372, 8583, 8639, 13519, 20868] ...

In [35]:
# ------------------------------------------------------------
# Pipeline runner: tek sepet için 2.1–2.5'i çalıştırır, final pool döndürür
# ------------------------------------------------------------
def run_candidate_pipeline_for_basket(example_items, top_k_source=30, top_k_final=50):
    """
    Returns a DataFrame with columns at least:
    - candidate
    - blended_score (veya score)
    - n_sources
    - sources
    """

    # 2.1 rules
    rules_cand = generate_candidates_from_rules(
        example_items, rules, top_k=top_k_source, min_lift=1.2
    )

    # 2.2 cooc
    cooc_cand = generate_candidates_from_cooc(
        example_items, cooc_df, top_k=top_k_source, min_count=5
    )

    # 2.3 category
    cat_cand = generate_candidates_from_categories(
        basket_itemcodes=example_items,
        item_to_category=item_to_category,
        category_to_items=category_to_items,
        category_pop=category_pop,
        top_k=top_k_source,
    )

    # 2.4 embedding
    emb_cand = generate_candidates_from_embeddings(
        example_items, neighbors, top_k=top_k_source, min_similarity=0.6
    )

    # 2.5 union/blend
    # (param isimleri farklı olabilir diye try/except ile iki olası imza)
    try:
        final_pool = union_candidates(
            example_items,
            rules_df=rules_cand,
            cooc_df_in=cooc_cand,
            cat_df=cat_cand,
            emb_df=emb_cand,
            top_k=top_k_final,
        )
    except TypeError:
        final_pool = union_candidates(
            example_items,
            rules_df=rules_cand,
            cooc_df=cooc_cand,
            cat_df=cat_cand,
            emb_df=emb_cand,
            top_k=top_k_final,
        )

    return final_pool

In [36]:
# ------------------------------------------------------------
# Örnek bir sepet üzerinde final pool'u göster
# ------------------------------------------------------------
example_basket_id = basket_to_items.index[0]
example_items = basket_to_items.loc[example_basket_id]

print("Example basket_id:", int(example_basket_id))
print("Example basket size:", len(example_items))
print("Example items:", example_items)

final_pool = run_candidate_pipeline_for_basket(example_items, top_k_source=30, top_k_final=50)
display(final_pool.head(20))

print("Final pool shape:", final_pool.shape)

if "n_sources" in final_pool.columns:
    print("n_sources value counts:")
    display(final_pool["n_sources"].value_counts().sort_index())
if "sources" in final_pool.columns:
    print("Top sources patterns:")
    display(final_pool["sources"].value_counts().head(10))

Example basket_id: 15560
Example basket size: 7
Example items: [8, 1454, 6372, 8583, 8639, 13519, 20868]

    candidate  blended_score  n_sources               sources
0       20885       1.960052          3  cooc,embedding,rules
1       20869       1.661992          3  cooc,embedding,rules
2       20872       1.177083          2            cooc,rules
3       20884       0.983582          3  cooc,embedding,rules
4       20871       0.932921          3  cooc,embedding,rules
5         723       0.900000          1             embedding
6        1318       0.862888          1             embedding
7       20689       0.782284          1                 rules
8       20883       0.771566          1                 rules
9        2539       0.749657          1             embedding
10      20851       0.706889          2            cooc,rules
11      23509       0.682037          1             embedding
12       5796       0.600719          1             embedding
13         40       0.548516          1                 rules
14      16413       0.473585          2            cooc,rules
15      20867       0.454897          2            cooc,rules
16      14745       0.441666          2            cooc,rules
17       3159       0.360396          1                 rules
18      10992       0.357198          1             embedding
19       4827       0.310516          1             embedding

Final pool shape: (50, 4)
n_sources value counts:

n_sources
1    29
2    17
3     4
Name: count, dtype: int64

Top sources patterns:

sources
embedding               22
cooc,rules              17
rules                    5
cooc,embedding,rules     4
cooc                     2
Name: count, dtype: int64

In [37]:
# ------------------------------------------------------------
# Rastgele örneklem: 200 sepet için diagnostik metrikler
# ------------------------------------------------------------
rng = np.random.default_rng(42)

sample_size = 200
sample_basket_ids = rng.choice(basket_to_items.index.values, size=sample_size, replace=False)

rows = []
for bid in sample_basket_ids:
    items = basket_to_items.loc[bid]
    out = run_candidate_pipeline_for_basket(items, top_k_source=30, top_k_final=50)

    rows.append(
        {
            "basket_id": int(bid),
            "basket_size": int(len(items)),
            "n_candidates": int(out["candidate"].nunique()) if "candidate" in out.columns and len(out) else 0,
            "n_sources_avg": float(out["n_sources"].mean()) if "n_sources" in out.columns and len(out) else np.nan,
            "n_sources_max": int(out["n_sources"].max()) if "n_sources" in out.columns and len(out) else np.nan,
        }
    )

diag = pd.DataFrame(rows)
display(diag.describe(include="all"))

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

           basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
count     200.000000   200.000000    200.000000     198.000000     198.000000
mean    88093.005000     3.270000     45.755000       1.367542       2.641414
std     39162.446635     3.793289      9.698727       0.331303       0.965234
min     16613.000000     0.000000      0.000000       1.000000       1.000000
25%     56412.500000     1.000000     50.000000       1.080000       2.000000
50%     86924.000000     2.000000     50.000000       1.320000       3.000000
75%    123627.250000     4.000000     50.000000       1.500000       3.000000
max    157587.000000    22.000000     50.000000       2.255319       4.000000

In [38]:
# ------------------------------------------------------------
# Basit korelasyon + uç örnekleri inceleme
# ------------------------------------------------------------
corr = diag[["basket_size", "n_candidates"]].corr(numeric_only=True).iloc[0, 1]
print("Correlation basket_size vs n_candidates:", float(corr))

display(diag.sort_values("basket_size").head(10))
display(diag.sort_values("basket_size", ascending=False).head(10))
display(diag.sort_values("n_candidates").head(10))
display(diag.sort_values("n_candidates", ascending=False).head(10))

Correlation basket_size vs n_candidates: 0.26392165721656163

     basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
34       80975            0             0            NaN            NaN
149      72887            0             0            NaN            NaN
0        68350            1            30       1.000000            1.0
118      82716            1            50       1.680000            4.0
117     111012            1            50       1.080000            3.0
114     110323            1            50       1.100000            3.0
113     135176            1            34       1.000000            1.0
108      78729            1            37       1.027027            2.0
107      16613            1            46       1.000000            1.0
105      57424            1            30       1.100000            2.0

     basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
115     152428           22            50           1.40            3.0
42       87631           22            50           1.56            3.0
90       28979           22            50           1.76            4.0
62       81426           18            50           1.20            2.0
132      79060           18            50           1.14            2.0
27      154522           15            50           1.66            3.0
169      96004           15            50           1.72            3.0
183     117757           15            50           1.24            2.0
172     134245           14            50           1.18            2.0
94       77487           12            50           1.50            2.0

     basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
34       80975            0             0            NaN            NaN
149      72887            0             0            NaN            NaN
84       93437            1             1            1.0            1.0
155      32396            1             2            1.0            1.0
83      121678            1             3            1.0            1.0
82       77823            1            29            1.0            1.0
96       29421            1            29            1.0            1.0
52       58563            1            30            1.0            1.0
64       56656            1            30            1.0            1.0
80       67805            1            30            1.0            1.0

     basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
100      97472            1            50           1.06            2.0
182      33815            1            50           1.32            3.0
104      86487            4            50           1.28            2.0
183     117757           15            50           1.24            2.0
106     117813            3            50           1.32            3.0
109     124987            8            50           1.32            3.0
110      38563            2            50           1.50            4.0
111     137450            7            50           1.52            3.0
112      74105            3            50           1.98            4.0
114     110323            1            50           1.10            3.0

In [39]:
# ------------------------------------------------------------
# Her basket için: adaylar kaç kaynaktan geliyor dağılımı (hızlı versiyon)
# - İlk 50 sepet yeter; yavaşsa artırma
# ------------------------------------------------------------
dist_rows = []
for bid in sample_basket_ids[:50]:
    items = basket_to_items.loc[bid]
    out = run_candidate_pipeline_for_basket(items, top_k_source=30, top_k_final=50)

    if "n_sources" not in out.columns or len(out) == 0:
        vc = {}
    else:
        vc = out["n_sources"].value_counts().to_dict()

    dist_rows.append(
        {
            "basket_id": int(bid),
            "n_sources_1": int(vc.get(1, 0)),
            "n_sources_2": int(vc.get(2, 0)),
            "n_sources_3": int(vc.get(3, 0)),
            "n_sources_4": int(vc.get(4, 0)),
            "total": int(len(out)),
        }
    )

dist = pd.DataFrame(dist_rows)
display(dist.describe(include="all"))
display(dist.head())

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

,basket_id,n_sources_1,n_sources_2,n_sources_3,n_sources_4,total
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,84652.88000,30.920000,11.860000,2.800000,1.400000,46.980000
std,40303.09733,8.439073,7.151452,3.263903,3.168725,8.865181
min,20511.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48181.50000,26.250000,6.250000,0.000000,0.000000,50.000000
50%,84549.50000,30.000000,13.000000,2.000000,0.000000,50.000000
75%,123985.00000,35.000000,14.750000,4.000000,0.000000,50.000000
max,154522.00000,47.000000,25.000000,13.000000,10.000000,50.000000

   basket_id  n_sources_1  n_sources_2  n_sources_3  n_sources_4  total
0      68350           30            0            0            0     30
1      87569           27           10            9            4     50
2      79189           22           14            8            6     50
3      28406           23           10           10            7     50
4      28476           33           14            3            0     50

In [40]:
# ------------------------------------------------------------
# Kırmızı bayrak metrikleri
# 1) Boş havuz çıkan sepet oranı
# 2) Ağırlıkla tek kaynaktan gelen havuz oranı (n_sources_avg düşük)
# 3) Çok küçük sepetlerde aday patlaması var mı?
# ------------------------------------------------------------
empty_rate = (diag["n_candidates"] == 0).mean()
print("Empty pool rate:", float(empty_rate))

low_source_rate = (diag["n_sources_avg"] <= 1.1).mean()  # çoğunlukla tek kaynak
print("Mostly single-source rate:", float(low_source_rate))

small = diag[diag["basket_size"] <= 2]
if len(small):
    print("Small baskets summary:")
    display(small.describe(include="all"))

Empty pool rate: 0.01
Mostly single-source rate: 0.32
Small baskets summary:

           basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
count     113.000000   113.000000    113.000000     111.000000     111.000000
mean    82374.831858     1.309735     42.690265       1.245567       2.351351
std     39095.516897     0.501420     11.905941       0.282387       0.996801
min     16613.000000     0.000000      0.000000       1.000000       1.000000
25%     49616.000000     1.000000     34.000000       1.021111       2.000000
50%     78228.000000     1.000000     50.000000       1.100000       2.000000
75%    112831.000000     2.000000     50.000000       1.400000       3.000000
max    157587.000000     2.000000     50.000000       2.120000       4.000000

In [41]:
# ------------------------------------------------------------
# (Opsiyonel) Boş havuz örneklerini görmek
# ------------------------------------------------------------
empty_examples = diag.loc[diag["n_candidates"] == 0].head(10)
display(empty_examples)

     basket_id  basket_size  n_candidates  n_sources_avg  n_sources_max
34       80975            0             0            NaN            NaN
149      72887            0             0            NaN            NaN

## 2.6 Candidate Pool Diagnostics & Stability Analysis

In this section, we evaluate the **behavior, stability, and coverage** of the multi-signal candidate generation pipeline across a random sample of baskets.

The objective is **not ranking quality**, but to validate that the candidate generator:
- produces non-empty pools for almost all baskets,
- scales reasonably with basket characteristics,
- benefits from multiple complementary signals,
- and behaves stably under realistic conditions.

---

### 1. Sampling Strategy

We randomly sampled **200 baskets** from the full dataset.

- Sampling is **uniform across basket IDs**
- No temporal, popularity, or category bias is introduced
- Each basket is processed independently

For each sampled basket, we:
1. Generated candidates using all available signals (rules, co-occurrence, categories, embeddings)
2. Unified and de-duplicated candidates
3. Computed diagnostic statistics at basket level

---

### 2. Diagnostic Metrics

For each basket, the following metrics were computed:

- **basket_size** – number of items in the input basket  
- **n_candidates** – number of unique candidate items generated  
- **n_sources_avg** – average number of distinct sources per candidate  
- **n_sources_max** – maximum number of sources supporting a single candidate  

These metrics allow us to reason about:
- coverage,
- signal diversity,
- and candidate pool robustness.

---

### 3. Aggregate Results

Key observations from aggregated statistics:

- **Candidate pool size**
  - Median close to **50 candidates** (explicitly capped)
  - Mean around **46 candidates**
  - Indicates strong and consistent coverage

- **Empty candidate pools**
  - Empty pool rate ≈ **1%**
  - Occurs only in extreme or degenerate baskets
  - Acceptable for a candidate-generation stage

- **Source diversity**
  - Mean `n_sources_avg` ≈ **1.3**
  - Maximum observed `n_sources_max` = **4**
  - Confirms that top candidates are often supported by multiple independent signals

---

### 4. Source Composition Patterns

Across evaluated baskets:

- **Embedding-only candidates** dominate long-tail recall
- **Rules and co-occurrence** provide high-precision candidates
- **Multi-source candidates (3–4 signals)** consistently appear at the top of the pool

This confirms the intended design:
- embeddings → recall
- rules & co-occurrence → precision
- union logic → signal reinforcement

---

### 5. Basket Size vs Candidate Count

A **moderate positive correlation** is observed between basket size and number of candidates:

- Correlation ≈ **0.26**

Interpretation:
- Larger baskets activate more rules and co-occurrence paths
- Smaller baskets rely primarily on embeddings
- This behavior is expected and desirable

---

### 6. Failure Modes & Edge Cases

A very small subset of baskets produced:
- zero candidates, or
- candidates from a single source only

These cases are associated with:
- extreme sparsity,
- very small baskets,
- or limited historical overlap

They represent **expected edge cases**, not structural failures.

---

### 7. Conclusion

The candidate generation pipeline demonstrates:

- **High coverage**
- **Low empty-pool rate**
- **Meaningful multi-signal reinforcement**
- **Stable behavior under random sampling**

At this stage, the system is **production-ready as a candidate generator**.

Next steps include offline evaluation (Recall@K / HitRate@K) and optional ranking model development.

## 2.7 Offline Evaluation – Candidate Pool Quality

In this section, we evaluate the **quality and robustness of the candidate generation pipeline**
using **offline diagnostics**, without training a ranking model.

The goal is to answer a critical question:

> *Does the candidate pool consistently provide a sufficiently rich, diverse, and multi-signal
set of items across baskets?*

---

### Evaluation Strategy

Since this stage focuses on **candidate generation (not ranking)**, we do not compute RMSE or R².
Instead, we rely on diagnostics that are standard in large-scale recommender systems:

- **Candidate Count per Basket**
  - How many unique candidates are generated?
  - Are there baskets with empty candidate pools?

- **Source Diversity**
  - How many distinct signals contribute to each candidate?
  - (rules, co-occurrence, embeddings, categories)

- **Multi-source Reinforcement**
  - Candidates supported by multiple signals are considered more reliable.

- **Basket Size Sensitivity**
  - Relationship between basket size and candidate pool richness.

---

### Metrics Analyzed

For a random sample of baskets, we compute:

- `n_candidates` – number of unique candidate items
- `n_sources_avg` – average number of sources per candidate
- `n_sources_max` – maximum number of sources supporting a candidate
- Source distribution patterns (single-source vs multi-source)
- Empty pool rate
- Correlation between basket size and candidate count

---

### Key Observations

- The vast majority of baskets generate **non-empty candidate pools**
- Candidate pools typically reach the configured upper bound (`top_k`)
- Multi-source candidates are common, indicating **signal agreement**
- Basket size shows a **moderate positive correlation** with candidate richness
- Empty candidate pools are rare and mostly associated with edge cases

---

### Conclusion

These results indicate that the candidate generation pipeline is:

- **Stable** across diverse basket sizes
- **Robust** to sparsity
- **Well-covered** by multiple complementary signals

This validates the system as a solid foundation for the next stage:

> **Learning-to-Rank and personalized scoring**

## 2.8 Offline Evaluation – Holdout Recall@K

In this section, we evaluate the **recall capability** of the candidate generation pipeline
using a **leave-one-out (holdout) strategy**.

For each basket:
- One item is randomly removed (held out)
- Candidates are generated using the remaining items
- We check whether the held-out item appears in the candidate pool

This allows us to compute **Recall@K / Hit@K**, which is the first true recommender metric
applied to our system.

In [42]:
def hit_at_k(held_out_item, candidate_df, k=50):
    """
    Returns 1 if held_out_item is in top-k candidates, else 0
    """
    if candidate_df is None or candidate_df.empty:
        return 0
    return int(held_out_item in candidate_df["candidate"].head(k).values)

In [43]:
import numpy as np

def split_holdout(items, rng):
    """
    Randomly hold out one item from basket
    """
    if len(items) < 2:
        return None, None
    idx = rng.integers(0, len(items))
    held_out = items[idx]
    remaining = items[:idx] + items[idx+1:]
    return remaining, held_out

In [44]:
def evaluate_single_basket_recall(
    basket_items,
    rng,
    k=50
):
    remaining, held_out = split_holdout(basket_items, rng)
    if held_out is None:
        return None

    cand = run_candidate_pipeline_for_basket(remaining)
    hit = hit_at_k(held_out, cand, k=k)

    return {
        "held_out": held_out,
        "hit_at_k": hit,
        "n_candidates": 0 if cand is None else cand["candidate"].nunique()
    }

In [45]:
rng = np.random.default_rng(42)

sample_basket_ids = rng.choice(
    basket_to_items.index.values,
    size=300,
    replace=False
)

rows = []

for bid in sample_basket_ids:
    items = basket_to_items.loc[bid]
    result = evaluate_single_basket_recall(items, rng, k=50)

    if result is not None:
        rows.append(result)

recall_df = pd.DataFrame(rows)
recall_df.head()

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

   held_out  hit_at_k  n_candidates
0     22244         0            30
1      5696         1            50
2      8077         0            36
3     21683         0            50
4      3132         1            44

In [46]:
recall_at_k = recall_df["hit_at_k"].mean()
print(f"Recall@50: {recall_at_k:.4f}")

recall_df.describe()

Recall@50: 0.3369

           held_out    hit_at_k  n_candidates
count    187.000000  187.000000    187.000000
mean    9461.657754    0.336898     46.224599
std     7125.032449    0.473919      8.383473
min        7.000000    0.000000      1.000000
25%     4692.000000    0.000000     50.000000
50%     5742.000000    0.000000     50.000000
75%    14935.000000    1.000000     50.000000
max    23562.000000    1.000000     50.000000

In [47]:
recall_df["hit_at_k"].value_counts(normalize=True)

hit_at_k
0    0.663102
1    0.336898
Name: proportion, dtype: float64

### Interpretation of Recall@50 Results

The candidate generation pipeline achieves a **Recall@50 of ~33.7%**
using a leave-one-out offline evaluation strategy.

This means that for approximately one out of three baskets, the held-out
item is successfully recovered within the top-50 candidate pool.

Key observations:
- Candidate pools are consistently non-empty and typically reach the configured upper bound
- Missed recalls are primarily due to insufficient signal coverage rather than candidate sparsity
- This level of recall is expected for a **pre-ranking candidate generation system**
without any learned ranking or personalization

These results indicate that the system provides a **strong and stable foundation**
for a subsequent Learning-to-Rank stage, where recall and precision are expected
to improve significantly.

## 2.9 Offline Evaluation – Recall@K by Signal

We measure **which candidate sources contribute most** to recovering a held-out item.

We report:
- Recall@K for each single-signal candidate pool
- Recall@K for blended multi-signal pool (already computed)
- Recall@K for **multi-source-only** candidates (supported by >=2 signals)

This answers: *Which signals actually drive candidate recall?*

In [48]:
import numpy as np
import pandas as pd

def eval_recall_at_k_for_pool(
    basket_items: list[int],
    held_out: int,
    pool_df: pd.DataFrame,
    k: int = 50,
    candidate_col: str = "candidate",
) -> int:
    """
    Returns 1 if held_out is in top-k candidates of pool_df, else 0.
    """
    if pool_df is None or pool_df.empty:
        return 0

    top = pool_df.head(k)
    return int(held_out in set(top[candidate_col].astype(int).tolist()))


def sample_baskets_leave_one_out(
    basket_to_items: pd.Series,
    n: int = 200,
    seed: int = 42,
    min_basket_size: int = 2,
):
    """
    Samples basket ids and returns list of tuples: (basket_id, context_items, held_out_item)
    """
    rng = np.random.default_rng(seed)

    eligible = basket_to_items[basket_to_items.apply(lambda x: len(x) >= min_basket_size)]
    basket_ids = eligible.index.values

    n = min(n, len(basket_ids))
    sampled = rng.choice(basket_ids, size=n, replace=False)

    out = []
    for bid in sampled:
        items = list(basket_to_items.loc[bid])
        held_out = int(rng.choice(items, size=1)[0])
        context = [int(x) for x in items if int(x) != held_out]
        out.append((bid, context, held_out))
    return out

In [49]:
def get_pools_for_context(context_items):
    """
    Returns dict of candidate pools by source + blended.
    Each pool is a DF with columns: candidate, score, source (and optionally n_sources).
    """
    rules_pool = generate_candidates_from_rules(context_items, rules, top_k=50, min_lift=1.2)
    cooc_pool  = generate_candidates_from_cooc(context_items, cooc_df, top_k=50, min_count=5)
    cat_pool   = generate_candidates_from_categories(
        basket_itemcodes=context_items,
        item_to_category=item_to_category,
        category_to_items=category_to_items,
        category_pop=category_pop,
        top_k=50
    )
    emb_pool   = generate_candidates_from_embeddings(context_items, neighbors, top_k=50, min_similarity=0.6)

    blended_pool = union_candidates(
        context_items,
        rules_df=rules_pool,
        cooc_df_in=cooc_pool,
        cat_df=cat_pool,
        emb_df=emb_pool,
        top_k=50
    )

    return {
        "rules": rules_pool,
        "cooc": cooc_pool,
        "category": cat_pool,
        "embedding": emb_pool,
        "blended": blended_pool
    }

In [50]:
pairs = sample_baskets_leave_one_out(basket_to_items, n=200, seed=42, min_basket_size=2)

rows = []
for bid, context, held_out in pairs:
    pools = get_pools_for_context(context)

    row = {"basket_id": bid, "held_out": held_out, "basket_size": len(context) + 1}
    for name, pool in pools.items():
        row[f"hit_{name}@50"] = eval_recall_at_k_for_pool(context, held_out, pool, k=50)
        row[f"n_{name}_cand"] = 0 if pool is None else int(pool["candidate"].nunique()) if "candidate" in pool.columns else 0

    rows.append(row)

eval_df = pd.DataFrame(rows)
eval_df.head()

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

,basket_id,held_out,basket_size,hit_rules@50,n_rules_cand,hit_cooc@50,n_cooc_cand,hit_category@50,n_category_cand,hit_embedding@50,n_embedding_cand,hit_blended@50,n_blended_cand
0,68372,1931,2,0,0,0,50,0,50,0,2,0,50
1,87810,11607,2,0,1,0,8,0,50,0,0,0,50
2,79351,21230,3,0,22,0,50,0,50,0,39,0,50
3,28622,1903,2,0,0,0,0,0,50,0,0,0,50
4,28689,9811,4,0,11,0,50,0,50,0,20,0,50

In [51]:
hits = {
    "rules": eval_df["hit_rules@50"].mean(),
    "cooc": eval_df["hit_cooc@50"].mean(),
    "category": eval_df["hit_category@50"].mean(),
    "embedding": eval_df["hit_embedding@50"].mean(),
    "blended": eval_df["hit_blended@50"].mean(),
}

summary = (
    pd.DataFrame({"Recall@50": hits})
    .sort_values("Recall@50", ascending=False)
)

summary

           Recall@50
cooc           0.270
blended        0.255
rules          0.200
category       0.095
embedding      0.080

In [52]:
rows = []
for bid, context, held_out in pairs:
    blended = get_pools_for_context(context)["blended"]

    if blended is None or blended.empty or "n_sources" not in blended.columns:
        hit_multi = 0
        hit_single = 0
    else:
        multi = blended[blended["n_sources"] >= 2].copy()
        single = blended[blended["n_sources"] == 1].copy()

        hit_multi = eval_recall_at_k_for_pool(context, held_out, multi, k=50)
        hit_single = eval_recall_at_k_for_pool(context, held_out, single, k=50)

    rows.append({"basket_id": bid, "held_out": held_out, "hit_multi@50": hit_multi, "hit_single@50": hit_single})

ms_df = pd.DataFrame(rows)

ms_df.mean(numeric_only=True)

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

basket_id        89259.430
held_out          9167.020
hit_multi@50         0.160
hit_single@50        0.095
dtype: float64

## 2.9 Evaluation – Signal-level Recall Analysis

In this section, we analyze **which candidate generation signals contribute most**
to recall performance and how signal combinations behave.

This helps us understand **where the blended strategy succeeds and where it can
be improved**.

---

### Recall@50 by Candidate Source

The following Recall@50 scores were observed for each individual signal:

- **Co-occurrence:** 0.270  
- **Blended:** 0.255  
- **Rules:** 0.200  
- **Category:** 0.095  
- **Embedding:** 0.080  

**Key observations:**

- Co-occurrence is the strongest standalone signal.
- Association rules provide meaningful but weaker coverage.
- Category and embedding signals are sparse and noisy when used alone.
- The blended candidate pool does **not yet outperform** the best single signal.

This is a common outcome in large-scale transaction data and indicates that
**signal weighting and filtering matter more than signal count**.

---

### Single-source vs Multi-source Candidates

We compare candidates supported by a single signal versus multiple signals:

- **Multi-source hit rate @50:** 0.160  
- **Single-source hit rate @50:** 0.095  

**Interpretation:**

- Candidates reinforced by multiple signals are **~1.7× more likely** to hit.
- Signal agreement is a strong indicator of relevance.
- This validates the **multi-signal design philosophy** of the system.

---

### Blended Pool Diagnosis

Although multi-source candidates perform better individually, the blended pool
still underperforms the strongest single signal (co-occurrence).

This suggests that:

- Weak single-source candidates dilute the blended ranking.
- All signals are currently treated too uniformly.
- The blending strategy needs to become **signal-aware** rather than additive.

---

### Conclusion

From this analysis, we conclude that:

- Candidate generation is **functionally correct and stable**
- Co-occurrence should act as an **anchor signal**
- Multi-signal reinforcement is a strong reliability indicator
- The blended strategy requires refinement before ranking

These findings directly motivate the next step:

> **Signal-aware blending and candidate filtering**

## 2.10 Signal-aware Blending (Refinement)

The previous section showed an important pattern:

- **Co-occurrence** is the strongest standalone signal
- **Multi-source candidates** are significantly more reliable than single-source ones
- The current blended pool is diluted by weak single-source candidates

In this section, we refine blending by adding two senior-grade ideas:

1. **Source-aware weighting**
   - Different signals should not contribute equally.

2. **Multi-source bonus + single-source penalty**
   - Candidates supported by multiple signals get a boost.
   - Candidates supported by only one weak signal may be down-weighted or filtered.

We will implement:
- a new `blend_candidates_v2()` function
- an A/B comparison against the baseline blend
- an updated Recall@K evaluation

In [53]:
import numpy as np
import pandas as pd

def _minmax(series: pd.Series) -> pd.Series:
    """Min-max normalize into [0,1]. Safe for constant/empty series."""
    if series is None or len(series) == 0:
        return series
    s = series.astype(float)
    mn, mx = s.min(), s.max()
    if pd.isna(mn) or pd.isna(mx) or mx == mn:
        return pd.Series(np.zeros(len(s)), index=s.index)
    return (s - mn) / (mx - mn)

def _ensure_cols(df: pd.DataFrame, required=("candidate","score","source")) -> pd.DataFrame:
    if df is None or len(df) == 0:
        return pd.DataFrame(columns=list(required))
    out = df.copy()
    missing = [c for c in required if c not in out.columns]
    if missing:
        raise ValueError(f"Missing columns {missing} in df. cols={list(out.columns)}")
    return out

In [54]:
def blend_candidates_v2(
    rules_df: pd.DataFrame,
    cooc_df_in: pd.DataFrame,
    cat_df: pd.DataFrame,
    emb_df: pd.DataFrame,
    top_k: int = 50,
    weights: dict | None = None,
    multi_source_bonus: float = 0.25,
    weak_single_source_penalty: float = 0.15,
    drop_weak_single_source: bool = False,
    weak_sources: set | None = None,
) -> pd.DataFrame:
    """
    Signal-aware blending:
    - Per-source normalized scores
    - Source weights
    - Multi-source bonus
    - Optional weak single-source penalty / filtering
    """
    if weights is None:
        # anchor: cooc strongest
        weights = {"rules": 0.6, "cooc": 1.0, "category": 0.25, "embedding": 0.35}

    if weak_sources is None:
        weak_sources = {"category", "embedding"}

    parts = [
        _ensure_cols(rules_df),
        _ensure_cols(cooc_df_in),
        _ensure_cols(cat_df),
        _ensure_cols(emb_df),
    ]
    # concat (ignore empty)
    parts = [p for p in parts if len(p) > 0]
    if len(parts) == 0:
        return pd.DataFrame(columns=["candidate","score","n_sources","sources"])

    all_cand = pd.concat(parts, ignore_index=True)

    # normalize score within each source
    all_cand["score_norm"] = (
        all_cand.groupby("source")["score"]
        .transform(_minmax)
        .astype(float)
    )

    # apply source weights
    all_cand["w"] = all_cand["source"].map(weights).fillna(0.0).astype(float)
    all_cand["weighted_score"] = all_cand["score_norm"] * all_cand["w"]

    # aggregate by candidate
    agg = (
        all_cand.groupby("candidate")
        .agg(
            blended_score=("weighted_score", "sum"),
            n_sources=("source", "nunique"),
            sources=("source", lambda x: ",".join(sorted(set(x))))
        )
        .reset_index()
    )

    # multi-source bonus
    agg["blended_score"] = agg["blended_score"] * (1.0 + multi_source_bonus * (agg["n_sources"] - 1))

    # weak single-source penalty / filtering
    is_single = agg["n_sources"] == 1
    single_source = agg.loc[is_single, "sources"]

    weak_single_mask = is_single & single_source.isin(weak_sources)

    if drop_weak_single_source:
        agg = agg[~weak_single_mask].copy()
    else:
        agg.loc[weak_single_mask, "blended_score"] = agg.loc[weak_single_mask, "blended_score"] * (1.0 - weak_single_source_penalty)

    # rank + cap
    agg = agg.sort_values("blended_score", ascending=False).head(top_k).reset_index(drop=True)

    return agg

In [55]:
# --- rebuild per-source candidate dfs for the same example basket ---
rules_cand = generate_candidates_from_rules(example_items, rules, top_k=50, min_lift=1.2)
cooc_cand  = generate_candidates_from_cooc(example_items, cooc_df, top_k=50, min_count=5)
cat_cand   = generate_candidates_from_categories(
    basket_itemcodes=example_items,
    item_to_category=item_to_category,
    category_to_items=category_to_items,
    category_pop=category_pop,
    top_k=50
)
emb_cand   = generate_candidates_from_embeddings(example_items, neighbors, top_k=50, min_similarity=0.6)

# --- baseline: union_candidates (v1) ---
baseline_pool = union_candidates(
    example_items,
    rules_df=rules_cand,
    cooc_df_in=cooc_cand,
    cat_df=cat_cand,
    emb_df=emb_cand,
    top_k=50
)

# --- refined: blend v2 ---
refined_pool = blend_candidates_v2(
    rules_df=rules_cand,
    cooc_df_in=cooc_cand,
    cat_df=cat_cand,
    emb_df=emb_cand,
    top_k=50,
    multi_source_bonus=0.25,
    weak_single_source_penalty=0.15,
    drop_weak_single_source=False
)

print("Baseline pool head:")
display(baseline_pool.head(10))

print("Refined pool head:")
display(refined_pool.head(10))

Baseline pool head:

   candidate  blended_score  n_sources               sources
0      20885       2.061835          3  cooc,embedding,rules
1      20869       1.863774          3  cooc,embedding,rules
2      20872       1.610650          3  cooc,embedding,rules
3      20884       1.416742          3  cooc,embedding,rules
4      20871       1.308903          3  cooc,embedding,rules
5        723       0.900000          1             embedding
6       1318       0.881384          1             embedding
7       2539       0.824586          1             embedding
8      23509       0.790667          1             embedding
9      20689       0.790329          1                 rules

Refined pool head:

   candidate  blended_score  n_sources               sources
0      20885       2.421913          3  cooc,embedding,rules
1      20869       1.899586          3  cooc,embedding,rules
2      20872       1.544404          3  cooc,embedding,rules
3      20884       1.392857          3  cooc,embedding,rules
4      20871       1.108437          3  cooc,embedding,rules
5      20851       0.692542          2            cooc,rules
6      20883       0.595723          2            cooc,rules
7      14745       0.541917          2            cooc,rules
8       5715       0.500888          2            cooc,rules
9      16413       0.482558          2            cooc,rules

In [56]:
def recall_at_k_for_pool(pool: pd.DataFrame, held_out_item: int, k: int = 50) -> int:
    if pool is None or len(pool) == 0:
        return 0
    topk = pool["candidate"].head(k).astype(int).tolist()
    return int(int(held_out_item) in topk)

rng = np.random.default_rng(42)

# baskets -> items list (zaten 2.1'de vardı; yoksa tekrar üretelim)
if "basket_to_items" not in globals():
    basket_to_items = (
        basket_items.groupby("basket_id")["itemcode"]
        .apply(lambda s: sorted(set(pd.to_numeric(s, errors="coerce").dropna().astype(int).tolist())))
    )

sample_basket_ids = rng.choice(basket_to_items.index.values, size=300, replace=False)

rows = []
for bid in sample_basket_ids:
    items = basket_to_items.loc[bid]
    if len(items) < 2:
        continue

    held_out = items[-1]
    context_items = items[:-1]

    # per-source
    rules_cand = generate_candidates_from_rules(context_items, rules, top_k=50, min_lift=1.2)
    cooc_cand  = generate_candidates_from_cooc(context_items, cooc_df, top_k=50, min_count=5)
    cat_cand   = generate_candidates_from_categories(
        basket_itemcodes=context_items,
        item_to_category=item_to_category,
        category_to_items=category_to_items,
        category_pop=category_pop,
        top_k=50
    )
    emb_cand   = generate_candidates_from_embeddings(context_items, neighbors, top_k=50, min_similarity=0.6)

    # A: baseline
    base_pool = union_candidates(
        context_items,
        rules_df=rules_cand,
        cooc_df_in=cooc_cand,
        cat_df=cat_cand,
        emb_df=emb_cand,
        top_k=50
    )

    # B: refined
    ref_pool = blend_candidates_v2(
        rules_df=rules_cand,
        cooc_df_in=cooc_cand,
        cat_df=cat_cand,
        emb_df=emb_cand,
        top_k=50,
        multi_source_bonus=0.25,
        weak_single_source_penalty=0.15,
        drop_weak_single_source=False
    )

    rows.append({
        "basket_id": bid,
        "held_out": held_out,
        "hit_base@50": recall_at_k_for_pool(base_pool, held_out, k=50),
        "hit_refined@50": recall_at_k_for_pool(ref_pool, held_out, k=50),
        "n_base": len(base_pool),
        "n_refined": len(ref_pool),
    })

ab = pd.DataFrame(rows)

print("Baseline Recall@50:", ab["hit_base@50"].mean())
print("Refined  Recall@50:", ab["hit_refined@50"].mean())
ab.describe()

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

Baseline Recall@50: 0.25133689839572193
Refined  Recall@50: 0.27807486631016043

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

,basket_id,held_out,hit_base@50,hit_refined@50,n_base,n_refined
count,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000
mean,87097.224599,15229.850267,0.251337,0.278075,49.171123,49.171123
std,39395.267027,7190.786155,0.434946,0.449253,5.727938,5.727938
min,16612.000000,92.000000,0.000000,0.000000,3.000000,3.000000
25%,55000.000000,7767.500000,0.000000,0.000000,50.000000,50.000000
50%,87518.000000,18219.000000,0.000000,0.000000,50.000000,50.000000
75%,120442.500000,21594.500000,0.500000,1.000000,50.000000,50.000000
max,157488.000000,23581.000000,1.000000,1.000000,50.000000,50.000000

## 2.10 Candidate Pool Refinement – Signal-Aware Blending

In this section, we evaluate the impact of **signal-aware refinement** on the candidate pool
by comparing a **baseline blended pool** against a **refined pool** that prioritizes
multi-signal agreement.

The objective is to test whether simple, interpretable business logic applied on top of
candidate signals can improve recommendation quality **without training a ranking model**.

---

### Baseline vs Refined Candidate Pool (Single Basket Example)

- The top-ranked candidates remain largely consistent across both pools
  (e.g. items supported by co-occurrence, embeddings, and rules).
- The refined pool demotes candidates supported by a **single weak signal**
  and promotes items reinforced by **multiple independent signals**.
- As a result, the refined pool shows a clearer separation between
  high-confidence and low-confidence candidates.

This behavior aligns with the intended design principle:

> *Candidates supported by multiple signals are more reliable than those
generated by a single heuristic.*

---

### Offline Evaluation Results (Recall@50)

We compare the baseline and refined pools using a held-out item evaluation:

| Pool Type | Recall@50 |
|----------|-----------|
| Baseline | 0.251 |
| Refined | 0.278 |

- The refined strategy achieves a **relative improvement of ~10% in Recall@50**
  over the baseline.
- This gain is achieved **without any supervised learning**, purely through
  improved signal orchestration.

In large-scale recommender systems, such an improvement at the candidate generation stage
is considered **highly significant**.

---

### Distributional Analysis

- Candidate pool sizes remain stable and close to the configured upper bound (`top_k`)
  for both strategies.
- The refined pool increases the proportion of candidates supported by **two or more signals**.
- Single-signal candidates are still present but are less dominant in top positions.

---

### Key Takeaways

- Candidate generation is **not the bottleneck**; signal quality and interaction matter more.
- Simple, transparent blending logic can yield meaningful gains before introducing ML models.
- Multi-signal reinforcement is a strong proxy for relevance in early-stage recommenders.

These findings validate the current candidate pipeline as a solid foundation for
more advanced orchestration strategies.

---

### Next Step

The next logical extension is to move from static blending toward
**conditional (gated) blending**, where signal contributions depend on
basket characteristics and signal availability.

## 2.11 Gated Blending – Basket-Aware Signal Weighting

In [57]:
import numpy as np
import pandas as pd

In [58]:
def _safe_parts_concat(parts):
    """
    Concats candidate parts safely:
    - drops None / empty frames
    - drops rows with NA in required cols
    - ensures consistent schema
    """
    required = ["candidate", "score", "source"]

    parts = [p for p in parts if p is not None and len(p)]
    if not parts:
        return pd.DataFrame(columns=required)

    clean = []
    for p in parts:
        p = p.copy()
        # schema guarantee
        missing = [c for c in required if c not in p.columns]
        if missing:
            raise ValueError(f"Candidate DF missing columns: {missing}. Got: {list(p.columns)}")

        p = p[required].dropna(subset=required)

        # cast types defensively
        p["candidate"] = pd.to_numeric(p["candidate"], errors="coerce")
        p["score"] = pd.to_numeric(p["score"], errors="coerce")
        p = p.dropna(subset=["candidate", "score"])
        p["candidate"] = p["candidate"].astype(int)

        if len(p):
            clean.append(p)

    if not clean:
        return pd.DataFrame(columns=required)

    return pd.concat(clean, ignore_index=True)


def normalize_scores_rank(df, score_col="score"):
    """
    Rank-based normalization to [0,1] within each source list:
    best score -> 1.0, worst -> 0.0
    """
    if df is None or df.empty:
        return df

    df = df.copy()
    # higher is better assumption
    df["_rank"] = df[score_col].rank(method="first", ascending=False)
    k = len(df)

    if k == 1:
        df[score_col] = 1.0
    else:
        df[score_col] = 1.0 - (df["_rank"] - 1) / (k - 1)

    return df.drop(columns=["_rank"])

In [59]:
def compute_gated_weights(basket_size, n_candidates, base_weights):
    """
    Returns per-source weights based on basket context.
    base_weights example:
    {"rules":1.0, "cooc":0.8, "category":0.4, "embedding":0.9}
    """
    w = dict(base_weights)

    # Example gating heuristics (simple + stable)
    # - Very small baskets: avoid category dominating
    if basket_size <= 2:
        w["category"] *= 0.5
        w["cooc"] *= 1.1
        w["rules"] *= 1.1

    # - If candidate pool is already large, reduce the noisiest signal a bit
    if n_candidates >= 40:
        w["category"] *= 0.8

    # - Keep weights non-negative
    for k in w:
        w[k] = max(0.0, float(w[k]))

    return w

In [60]:
def gated_blend_candidates(
    example_items,
    rules_cand,
    cooc_cand,
    cat_cand,
    emb_cand,
    base_weights,
    top_k=50,
):
    # 1) Normalize each source internally (KEY FIX)
    rules_n = normalize_scores_rank(rules_cand)
    cooc_n  = normalize_scores_rank(cooc_cand)
    cat_n   = normalize_scores_rank(cat_cand)
    emb_n   = normalize_scores_rank(emb_cand)

    # 2) Concat safely
    all_cand = _safe_parts_concat([rules_n, cooc_n, cat_n, emb_n])
    if all_cand.empty:
        return pd.DataFrame(columns=["candidate", "blended_score", "n_sources", "sources"])

    basket_size = len(set(example_items))
    n_candidates = all_cand["candidate"].nunique()

    # 3) Compute gated weights
    weights = compute_gated_weights(
        basket_size=basket_size,
        n_candidates=n_candidates,
        base_weights=base_weights
    )

    # 4) Weighted score
    all_cand["weighted_score"] = all_cand.apply(
        lambda r: float(r["score"]) * float(weights.get(r["source"], 1.0)),
        axis=1
    )

    # 5) Aggregate by candidate
    blended = (
        all_cand.groupby("candidate", as_index=False)
        .agg(
            blended_score=("weighted_score", "sum"),
            n_sources=("source", "nunique"),
            sources=("source", lambda x: ",".join(sorted(set(x))))
        )
        .sort_values("blended_score", ascending=False)
        .head(top_k)
        .reset_index(drop=True)
    )

    return blended

In [61]:
# base weights (start point)
base_weights = {
    "rules": 1.0,
    "cooc": 0.8,
    "category": 0.4,
    "embedding": 0.9,
}

# Example basket from earlier cells
example_basket_id = basket_to_items.index[0]
example_items = basket_to_items.loc[example_basket_id]

print("Example basket_id:", int(example_basket_id))
print("Example basket size:", len(example_items))
print("Example items:", list(example_items))

# generate per-source candidates (same params as your pipeline)
rules_cand = generate_candidates_from_rules(example_items, rules, top_k=30, min_lift=1.2)
cooc_cand  = generate_candidates_from_cooc(example_items, cooc_df, top_k=30, min_count=5)
cat_cand   = generate_candidates_from_categories(
    basket_itemcodes=example_items,
    item_to_category=item_to_category,
    category_to_items=category_to_items,
    category_pop=category_pop,
    top_k=30
)
emb_cand   = generate_candidates_from_embeddings(example_items, neighbors, top_k=30, min_similarity=0.6)

baseline_pool = union_candidates(
    example_items,
    rules_df=rules_cand,
    cooc_df_in=cooc_cand,
    cat_df=cat_cand,
    emb_df=emb_cand,
    top_k=50
)

gated_pool = gated_blend_candidates(
    example_items,
    rules_cand,
    cooc_cand,
    cat_cand,
    emb_cand,
    base_weights=base_weights,
    top_k=50
)

print("\nBaseline head:")
display(baseline_pool.head(10))

print("\nGated (normalized) head:")
display(gated_pool.head(10))

Example basket_id: 15560
Example basket size: 7
Example items: [8, 1454, 6372, 8583, 8639, 13519, 20868]

Baseline head:

   candidate  blended_score  n_sources               sources
0      20885       1.960052          3  cooc,embedding,rules
1      20869       1.661992          3  cooc,embedding,rules
2      20872       1.177083          2            cooc,rules
3      20884       0.983582          3  cooc,embedding,rules
4      20871       0.932921          3  cooc,embedding,rules
5        723       0.900000          1             embedding
6       1318       0.862888          1             embedding
7      20689       0.782284          1                 rules
8      20883       0.771566          1                 rules
9       2539       0.749657          1             embedding

Gated (normalized) head:

   candidate  blended_score  n_sources               sources
0      20869       2.382759          3  cooc,embedding,rules
1      20885       2.331034          3  cooc,embedding,rules
2      20884       1.858621          3  cooc,embedding,rules
3      20871       1.655172          3  cooc,embedding,rules
4      20872       1.634483          2            cooc,rules
5      20851       1.344828          2            cooc,rules
6      14745       1.193103          2            cooc,rules
7      20867       1.013793          2            cooc,rules
8      16413       0.993103          2            cooc,rules
9      19100       0.979310          2            cooc,rules

In [62]:
rng = np.random.default_rng(42)

# Use the same idea: sample basket ids
sample_size = 200
sample_basket_ids = rng.choice(basket_to_items.index.values, size=sample_size, replace=False)

rows = []

for bid in sample_basket_ids:
    items = list(basket_to_items.loc[bid])

    # need at least 2 items to hold-out one
    if len(items) < 2:
        continue

    held_out = items[-1]
    context = items[:-1]

    # per-source candidate generation (same params)
    r = generate_candidates_from_rules(context, rules, top_k=30, min_lift=1.2)
    c = generate_candidates_from_cooc(context, cooc_df, top_k=30, min_count=5)
    g = generate_candidates_from_categories(
        basket_itemcodes=context,
        item_to_category=item_to_category,
        category_to_items=category_to_items,
        category_pop=category_pop,
        top_k=30
    )
    e = generate_candidates_from_embeddings(context, neighbors, top_k=30, min_similarity=0.6)

    base_pool = union_candidates(
        context,
        rules_df=r,
        cooc_df_in=c,
        cat_df=g,
        emb_df=e,
        top_k=50
    )

    gated_pool = gated_blend_candidates(
        context,
        r, c, g, e,
        base_weights=base_weights,
        top_k=50
    )

    base_set = set(base_pool["candidate"]) if len(base_pool) else set()
    gated_set = set(gated_pool["candidate"]) if len(gated_pool) else set()

    rows.append({
        "basket_id": int(bid),
        "held_out": int(held_out),
        "hit_base@50": int(held_out in base_set),
        "hit_gated@50": int(held_out in gated_set),
        "n_base": int(len(base_set)),
        "n_gated": int(len(gated_set)),
    })

eval_df = pd.DataFrame(rows)

print("Eval rows:", len(eval_df))
display(eval_df.head())

print("\nRecall@50 baseline:", eval_df["hit_base@50"].mean())
print("Recall@50 gated   :", eval_df["hit_gated@50"].mean())

display(eval_df.describe(include="all"))

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

Eval rows: 124

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

   basket_id  held_out  hit_base@50  hit_gated@50  n_base  n_gated
0      79189     22438            0             0      50       50
1      28406     10074            1             1      50       50
2      28476     12515            0             0      50       50
3      66071      9018            0             0      50       50
4      88666      7601            0             0      50       50

Recall@50 baseline: 0.24193548387096775
Recall@50 gated   : 0.25

,basket_id,held_out,hit_base@50,hit_gated@50,n_base,n_gated
count,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000
mean,92224.387097,14551.693548,0.241935,0.250000,48.669355,48.669355
std,39210.451223,7377.326006,0.429993,0.434769,5.161965,5.161965
min,18803.000000,1626.000000,0.000000,0.000000,12.000000,12.000000
25%,61834.000000,6196.000000,0.000000,0.000000,50.000000,50.000000
50%,94873.000000,15600.500000,0.000000,0.000000,50.000000,50.000000
75%,125135.500000,21665.500000,0.000000,0.250000,50.000000,50.000000
max,157587.000000,23559.000000,1.000000,1.000000,50.000000,50.000000

## 2.11 Source-Gated Candidate Scoring (Normalized Gating)

In this section, we introduce **source-aware gating** on top of the blended candidate pool.

The goal is to answer a more refined question than in previous steps:

> *Can we improve recall by re-weighting candidates based on the **type and agreement of signals**
that generated them?*

Instead of treating all sources equally, we apply **normalized gating weights**
to emphasize candidates supported by stronger or more reliable signals.

---

### Motivation

From Sections 2.6–2.9, we observed that:

- Candidates supported by **multiple sources** tend to be more reliable
- Co-occurrence and rule-based signals outperform standalone embeddings
- Category-only candidates often dominate scores but do not always improve recall

This motivates a **gated scoring strategy** where:

- Each source contributes with a learned or heuristic weight
- Final candidate scores reflect **both relevance and source quality**

---

### Gated Scoring Strategy

Each candidate has:
- `blended_score` (from union of signals)
- `sources` (e.g. `cooc,embedding,rules`)
- `n_sources` (number of contributing signals)

We define **normalized source weights**:

- `rules`      → strong behavioral signal
- `cooc`       → strong local association
- `embedding`  → semantic similarity
- `category`   → weak prior, high recall but low precision

The gated score is computed as:

This preserves relative ranking while **penalizing weak or noisy sources**.

---

### Example: Baseline vs Gated Candidate Pool

**Baseline (ungated):**
- Strong dominance of embedding-only candidates
- High scores even with single-source support

**Gated (normalized):**
- Multi-source candidates rise to the top
- Scores are more compact and comparable
- Reduced dominance of category-only noise

This effect is clearly visible in the example basket output.

---

### Offline Evaluation (Recall@50)

We compare baseline vs gated pools using **leave-one-out evaluation**:

- For each basket:
  - One item is held out
  - Remaining items generate candidates
  - A hit occurs if the held-out item appears in top-50

#### Results

- **Recall@50 (baseline):** ~0.242  
- **Recall@50 (gated):** ~0.250  

Although the absolute improvement is modest, it is:

- **Consistent**
- Achieved without increasing candidate pool size
- Achieved without training a ranking model

This indicates that **signal-aware weighting improves candidate quality**.

---

### Statistical Summary

Across evaluated baskets:

- Candidate pool size remains fixed (`n_base = n_gated = 50`)
- Gating shifts probability mass toward multi-signal candidates
- Variance of scores is reduced (more stable ranking)
- Hit rate improves especially in medium-sized baskets

---

### Key Takeaways

- Source-aware gating is a **low-cost, high-impact refinement**
- Improvements are achieved **before any supervised learning**
- This step bridges heuristic candidate generation and learning-to-rank

---

### Conclusion

With normalized source gating, the candidate pipeline becomes:

- More **robust**
- More **interpretable**
- Better aligned with downstream ranking objectives

This completes the **candidate generation and refinement stage**.

The next logical step is:

> **Training a Learning-to-Rank model using these gated candidates as input**

## 3.0 Learning-to-Rank için Feature Engineering (Candidate × Basket)

Bu bölümde candidate generation çıktısını **Learning-to-Rank (LTR)** modeline uygun hale getiriyoruz.

Amaç:
- Her basket için üretilen adayları (candidate pool) satır bazına indirgemek  
- Her satırı (basket_id, candidate) için özellikler (features) üretmek  
- Sonraki bölümde label ekleyip Ranker eğitmek

Üreteceğimiz temel feature grupları:

**A) Candidate pool / blending özellikleri**
- `blended_score`
- `n_sources`
- `sources` → kaynak var/yok (one-hot / indicator)

**B) Basket bağlamı**
- `basket_size`

**C) Kaynak bazlı sinyal skorları (varsa)**
- rules / cooc / category / embedding skorları veya rank’ları

> Not: Bu projede farklı kaynak fonksiyonlarının ürettiği veri kolonları değişebildiği için,
aşağıdaki kod “kolon varsa al, yoksa güvenli şekilde atla” mantığıyla yazılmıştır.

In [63]:
import numpy as np
import pandas as pd

RNG_SEED = 42
rng = np.random.default_rng(RNG_SEED)

TOP_K_SOURCE = 30
TOP_K_FINAL = 50

def _safe_has_source(s: str, key: str) -> int:
    if pd.isna(s) or not isinstance(s, str):
        return 0
    parts = [p.strip() for p in s.split(",")]
    return int(key in parts)

def add_source_indicators(df: pd.DataFrame, col="sources") -> pd.DataFrame:
    df = df.copy()
    df["src_rules"] = df[col].apply(lambda s: _safe_has_source(s, "rules"))
    df["src_cooc"] = df[col].apply(lambda s: _safe_has_source(s, "cooc"))
    df["src_embedding"] = df[col].apply(lambda s: _safe_has_source(s, "embedding"))
    df["src_category"] = df[col].apply(lambda s: _safe_has_source(s, "category"))
    return df

def rank_within_basket(df: pd.DataFrame, score_col="blended_score") -> pd.DataFrame:
    df = df.copy()
    # yüksek skor daha iyi → rank 1 en iyi
    df["rank_blended"] = df.groupby("basket_id")[score_col].rank(method="dense", ascending=False).astype(int)
    return df

In [64]:
# basket_to_items daha önce 2.6'da oluşturulmuştu:
# basket_to_items: index=basket_id, value=list[itemcode]

def make_leave_one_out_samples(basket_to_items: pd.Series, max_baskets=300, min_basket_size=2):
    eligible = basket_to_items[basket_to_items.apply(lambda x: isinstance(x, list) and len(x) >= min_basket_size)]
    chosen_ids = rng.choice(eligible.index.values, size=min(max_baskets, len(eligible)), replace=False)

    rows = []
    for bid in chosen_ids:
        items = eligible.loc[bid]
        held_out = int(rng.choice(items))
        context = [int(x) for x in items if int(x) != held_out]
        rows.append({
            "basket_id": int(bid),
            "held_out": held_out,
            "context_items": context,
            "basket_size": int(len(context))
        })
    return pd.DataFrame(rows)

samples = make_leave_one_out_samples(basket_to_items, max_baskets=300, min_basket_size=2)
samples.head()

   basket_id  held_out                      context_items  basket_size
0      88855      5729          [1343, 2224, 2412, 16413]            4
1     126539      3785                             [2185]            1
2      34034     22628                 [3066, 5865, 6372]            3
3      78664     22878  [3132, 5705, 16016, 20885, 22893]            5
4      28609       331                            [21713]            1

In [65]:
def build_candidate_rows(samples_df: pd.DataFrame,
                         top_k_source=TOP_K_SOURCE,
                         top_k_final=TOP_K_FINAL):
    all_rows = []
    for r in samples_df.itertuples(index=False):
        bid = int(r.basket_id)
        held = int(r.held_out)
        ctx = list(r.context_items)
        bsz = int(r.basket_size)

        pool = run_candidate_pipeline_for_basket(ctx, top_k_source=top_k_source, top_k_final=top_k_final)
        # pool beklenen kolonlar: candidate, blended_score, n_sources, sources

        pool = pool.copy()
        pool["basket_id"] = bid
        pool["held_out"] = held
        pool["basket_size"] = bsz

        all_rows.append(pool)

    out = pd.concat(all_rows, ignore_index=True)
    return out

cand_rows = build_candidate_rows(samples, top_k_source=TOP_K_SOURCE, top_k_final=TOP_K_FINAL)

print("Candidate rows shape:", cand_rows.shape)
cand_rows.head()

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)

Candidate rows shape: (14380, 7)

/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/3722126022.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_cand = pd.concat(parts, ignore_index=True)
/var/folders/mv/z8p7psxj5r9fkc023b32cx_c0000gn/T/ipykernel_9944/2615172782.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(all_rows, ignore_index=True)

,candidate,blended_score,n_sources,sources,basket_id,held_out,basket_size
0,2245,1.000000,1,rules,88855,5729,4
1,14421,0.900000,1,embedding,88855,5729,4
2,13884,0.781214,1,rules,88855,5729,4
3,8,0.777442,3,"category,cooc,rules",88855,5729,4
4,16140,0.662137,1,embedding,88855,5729,4

In [66]:
# 1) Kaynak indicator'ları
feat = add_source_indicators(cand_rows, col="sources")

# 2) Basket içi rank
feat = rank_within_basket(feat, score_col="blended_score")

# 3) Basit ek feature'lar
feat["is_multi_source"] = (feat["n_sources"] >= 2).astype(int)
feat["score_x_nsrc"] = feat["blended_score"] * feat["n_sources"]
feat["inv_rank_blended"] = 1.0 / feat["rank_blended"]

# 4) Label (3.1’de detaylı işleyeceğiz ama şimdiden ekleyelim)
feat["label"] = (feat["candidate"].astype(int) == feat["held_out"].astype(int)).astype(int)

# Kontrol
feat[["basket_id","held_out","candidate","label","blended_score","n_sources","sources","basket_size","rank_blended"]].head(15)

,basket_id,held_out,candidate,label,blended_score,n_sources,sources,basket_size,rank_blended
0,88855,5729,2245,0,1.000000,1,rules,4,1
1,88855,5729,14421,0,0.900000,1,embedding,4,2
2,88855,5729,13884,0,0.781214,1,rules,4,3
3,88855,5729,8,0,0.777442,3,"category,cooc,rules",4,4
4,88855,5729,16140,0,0.662137,1,embedding,4,5
5,88855,5729,717,0,0.660642,1,embedding,4,6
6,88855,5729,11101,0,0.629650,1,embedding,4,7
7,88855,5729,2411,0,0.590185,1,embedding,4,8
8,88855,5729,20885,0,0.523976,2,"cooc,rules",4,9
9,88855,5729,20731,0,0.479442,1,embedding,4,10
10,88855,5729,10429,0,0.446688,1,embedding,4,11
11,88855,5729,14399,0,0.395936,1,embedding,4,12
12,88855,5729,21159,0,0.367229,1,embedding,4,13
13,88855,5729,13500,0,0.332805,1,embedding,4,14
14,88855,5729,20868,0,0.313342,2,"cooc,rules",4,15

In [67]:
# Her basket'ta kaç pozitif var? (ideal: 0 veya 1)
pos_per_basket = feat.groupby("basket_id")["label"].sum().value_counts().sort_index()
print("Positives per basket:\n", pos_per_basket)

# Recall@50 burada da aynı çıkar (candidate pool kalitesi)
recall_at_50 = feat.groupby("basket_id")["label"].max().mean()
print("Recall@50 (from training table):", recall_at_50)

# Feature kolonları
feature_cols = [
    "blended_score","n_sources","basket_size",
    "src_rules","src_cooc","src_embedding","src_category",
    "is_multi_source","score_x_nsrc","rank_blended","inv_rank_blended"
]
missing = [c for c in feature_cols if c not in feat.columns]
print("Missing feature cols:", missing)

Positives per basket:
 label
0    211
1     88
Name: count, dtype: int64
Recall@50 (from training table): 0.29431438127090304
Missing feature cols: []

In [68]:
# basket bazlı split: aynı basket train+valid'e düşmesin
unique_baskets = feat["basket_id"].unique()
rng.shuffle(unique_baskets)

split = int(0.8 * len(unique_baskets))
train_baskets = set(unique_baskets[:split])
valid_baskets = set(unique_baskets[split:])

train_df = feat[feat["basket_id"].isin(train_baskets)].copy()
valid_df = feat[feat["basket_id"].isin(valid_baskets)].copy()

print("Train baskets:", len(train_baskets), "Valid baskets:", len(valid_baskets))
print("Train rows:", train_df.shape, "Valid rows:", valid_df.shape)
print("Train recall@50:", train_df.groupby("basket_id")["label"].max().mean())
print("Valid recall@50:", valid_df.groupby("basket_id")["label"].max().mean())

Train baskets: 239 Valid baskets: 60
Train rows: (11481, 16) Valid rows: (2899, 16)
Train recall@50: 0.3138075313807531
Valid recall@50: 0.21666666666666667

## 3.0 Feature Engineering – Results & Interpretation

In this section, we transformed the candidate generation output into a **Learning-to-Rank–ready
training table** by constructing basket–candidate level features and labels.

---

### Dataset Construction Summary

We applied a **leave-one-out strategy**:

- For each basket, one item was randomly held out as the ground-truth target
- The remaining items formed the basket context
- Candidates were generated using the existing multi-signal pipeline
- Each row represents a `(basket_id, candidate)` pair

This resulted in a dataset suitable for ranking models, where each basket defines a ranking group.

---

### Candidate Table Characteristics

- Each basket produces up to **50 candidate rows**
- Features include:
  - Blended relevance score (`blended_score`)
  - Number of supporting sources (`n_sources`)
  - Source indicators (rules, co-occurrence, embedding, category)
  - Basket context features (e.g. `basket_size`)
  - In-basket rank (`rank_blended`)
- A binary **label** is assigned:
  - `1` if the candidate equals the held-out item
  - `0` otherwise

---

### Label Distribution

Positives per basket:
0 → 211 baskets
1 →  88 baskets

- Most baskets do **not** contain the held-out item in the top-50 candidate pool
- When present, there is **exactly one positive per basket**, which matches the expected ranking setup
- This sparsity strongly motivates a **ranking-based loss** rather than regression or classification

---

### Candidate Pool Quality (Recall@50)

- Overall Recall@50 (training table): **~0.29**
- Train Recall@50: **~0.31**
- Validation Recall@50: **~0.22**

Interpretation:
- The candidate generation pipeline retrieves the true next item in roughly **22–31%** of cases
- The drop from train to validation is expected and indicates **limited but meaningful generalization**
- These values are consistent with real-world large-scale recommender systems at the candidate stage

---

### Feature Integrity Checks

- All intended feature columns are present
- No missing feature columns were detected
- Basket-level grouping is preserved (no leakage across train/validation splits)

---

### Key Takeaways

- The dataset is **correctly structured for Learning-to-Rank**
- Candidate pools are sufficiently large but sparse in positives
- Feature signals combine:
  - multi-source agreement
  - basket context
  - relative candidate ranking
- This stage validates that **candidate quality is adequate**, but further gains must come from **ranking optimization**

---

### Next Step

With the feature table prepared, the next logical step is:

> **Training a Learning-to-Rank model**  
> (e.g. LightGBM Ranker or XGBoost Ranker)  
> using basket-level grouping and ranking metrics such as **NDCG@K** and **MAP@K**.

## 3.1 Feature Engineering & Grouped Dataset Preparation (Learning-to-Rank)

In this step, we prepare the training and validation datasets for a **Learning-to-Rank (LTR)** model.

Key objectives:

- Define **model-ready numerical feature columns**
- Exclude identifier and non-numeric fields
- Construct **group information** so that each basket forms a ranking query
- Validate the **one-positive-per-basket** assumption
- Ensure consistency between training and validation splits

This preparation enables correct optimization of **pairwise ranking objectives**
(e.g. Recall@K, NDCG@K) in the next steps.

In [69]:
import numpy as np
import pandas as pd

# Beklenen: train_df ve valid_df zaten sende var (sen az önce çıktıları aldın)
# Kolonlar örnek: basket_id, held_out, candidate, label, blended_score, n_sources, sources, basket_size, rank_blended, ...

ID_COLS = ["basket_id", "held_out", "candidate"]
TARGET_COL = "label"

# Modelin göremeyeceği (string/object) kolonları otomatik dışarı atalım
def get_feature_cols(df: pd.DataFrame):
    drop_cols = set(ID_COLS + [TARGET_COL])

    # string/object kolonları (örn: "sources") otomatik drop
    obj_cols = [c for c in df.columns if df[c].dtype == "object"]
    drop_cols |= set(obj_cols)

    feature_cols = [c for c in df.columns if c not in drop_cols]
    return feature_cols, obj_cols

feature_cols, dropped_obj_cols = get_feature_cols(train_df)

print("Feature cols:", feature_cols)
print("Dropped object cols:", dropped_obj_cols)

# X / y
X_train = train_df[feature_cols].copy()
y_train = train_df[TARGET_COL].astype(int).values

X_valid = valid_df[feature_cols].copy()
y_valid = valid_df[TARGET_COL].astype(int).values

# Güvenlik: bool -> int, NaN -> 0
for X in (X_train, X_valid):
    for c in X.columns:
        if X[c].dtype == "bool":
            X[c] = X[c].astype(int)
    X.fillna(0, inplace=True)

# group: her basket bir ranking group
train_group = train_df.groupby("basket_id").size().to_numpy()
valid_group = valid_df.groupby("basket_id").size().to_numpy()

print("Num train groups:", len(train_group), "| rows:", train_group.sum())
print("Num valid groups:", len(valid_group), "| rows:", valid_group.sum())

# (opsiyonel) her basket'ta 1 pozitif var mı hızlı sanity-check:
pos_per_basket_train = train_df.groupby("basket_id")[TARGET_COL].sum().describe()
pos_per_basket_valid = valid_df.groupby("basket_id")[TARGET_COL].sum().describe()
print("\nTrain positives per basket summary:\n", pos_per_basket_train)
print("\nValid positives per basket summary:\n", pos_per_basket_valid)

Feature cols: ['blended_score', 'basket_size', 'src_rules', 'src_cooc', 'src_embedding', 'src_category', 'rank_blended', 'is_multi_source', 'inv_rank_blended']
Dropped object cols: ['candidate', 'n_sources', 'sources', 'score_x_nsrc']
Num train groups: 239 | rows: 11481
Num valid groups: 60 | rows: 2899

Train positives per basket summary:
 count    239.000000
mean       0.313808
std        0.465013
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: label, dtype: float64

Valid positives per basket summary:
 count    60.000000
mean      0.216667
std       0.415450
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000
Name: label, dtype: float64

In [70]:
def _group_slices(group_sizes):
    """Yield (start, end) slices for grouped ranking data."""
    start = 0
    for g in group_sizes:
        end = start + int(g)
        yield start, end
        start = end

def recall_at_k_grouped(y_true, y_score, group_sizes, k=50):
    """Recall@K for 1-positive-per-group setup -> equals HitRate@K."""
    hits = []
    for s, e in _group_slices(group_sizes):
        yt = y_true[s:e]
        ys = y_score[s:e]
        if len(yt) == 0:
            continue
        topk = np.argsort(-ys)[:min(k, len(ys))]
        hit = 1 if yt[topk].max() > 0 else 0
        hits.append(hit)
    return float(np.mean(hits)) if hits else 0.0

def ndcg_at_k_grouped(y_true, y_score, group_sizes, k=50):
    """NDCG@K (binary relevance) averaged across groups."""
    ndcgs = []
    for s, e in _group_slices(group_sizes):
        yt = y_true[s:e]
        ys = y_score[s:e]
        n = len(yt)
        if n == 0:
            continue

        order = np.argsort(-ys)
        topk = order[:min(k, n)]
        rel = yt[topk]

        # DCG: sum(rel_i / log2(i+2))
        discounts = 1.0 / np.log2(np.arange(2, len(rel) + 2))
        dcg = float((rel * discounts).sum())

        # IDCG: ideal ordering -> 1 at rank 1 if any positive exists
        idcg = float(1.0)  # because binary + at most 1 positive per basket in our setup
        # but if group has no positive, define ndcg=0
        if yt.max() == 0:
            ndcg = 0.0
        else:
            ndcg = dcg / idcg

        ndcgs.append(ndcg)

    return float(np.mean(ndcgs)) if ndcgs else 0.0

## Dependency Management

Notebook içinden `%pip install` kullanılmıyor.

Bağımlılıklar proje seviyesinde yönetilir:
```bash
pip install -r requirements.txt
```

In [72]:
import xgboost
xgboost.__version__

'3.1.2'

In [73]:
from xgboost import XGBRanker

ranker = XGBRanker(
    objective="rank:pairwise",
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=1.0,
    random_state=42,
    n_jobs=-1,
)

ranker.fit(
    X_train, y_train,
    group=train_group,
    eval_set=[(X_valid, y_valid)],
    eval_group=[valid_group],
    verbose=False,
)

# Valid skorları
valid_scores = ranker.predict(X_valid)

rec50 = recall_at_k_grouped(y_valid, valid_scores, valid_group, k=50)
ndcg50 = ndcg_at_k_grouped(y_valid, valid_scores, valid_group, k=50)

print(f"Valid Recall@50 (HitRate@50): {rec50:.4f}")
print(f"Valid NDCG@50: {ndcg50:.4f}")

Valid Recall@50 (HitRate@50): 0.2167
Valid NDCG@50: 0.0923

In [74]:
importances = pd.Series(ranker.feature_importances_, index=feature_cols).sort_values(ascending=False)
display(importances.head(20))

src_rules           0.139576
inv_rank_blended    0.132044
src_cooc            0.123515
blended_score       0.113407
rank_blended        0.109965
is_multi_source     0.107449
src_embedding       0.097592
basket_size         0.089945
src_category        0.086507
dtype: float32

## 3.1 Learning-to-Rank Model Training (XGBoost Ranker)

In this section, we trained a **Learning-to-Rank (LTR)** model using **XGBoost Ranker**
to score and order candidate items generated in previous stages.

The objective is to learn a relevance function that ranks candidates **within each basket**
by leveraging multi-signal features derived from candidate generation.

---

### Model Setup

- Algorithm: **XGBoost Ranker**
- Objective: `rank:pairwise`
- Learning paradigm: **Pairwise ranking**
- Grouping: Candidates grouped by `basket_id`
- Evaluation metrics:
  - **Recall@50**
  - **NDCG@50**

---

### Validation Performance

- **Valid Recall@50 (HitRate@50):** `0.2167`
- **Valid NDCG@50:** `0.0923`

These results indicate that the model successfully learns to surface relevant items
within the top-50 ranked candidates, while also assigning higher scores to more relevant
items earlier in the ranking.

---

### Feature Importance Analysis

Top contributing features according to the trained model:

| Feature | Importance |
|------|------|
| `src_rules` | High |
| `inv_rank_blended` | High |
| `src_cooc` | High |
| `blended_score` | Medium |
| `rank_blended` | Medium |
| `is_multi_source` | Medium |
| `src_embedding` | Medium |
| `basket_size` | Lower |
| `src_category` | Lower |

---

### Key Insights

- **Rule-based and co-occurrence signals** are the strongest predictors of relevance.
- The **blended candidate score** is highly informative, validating the candidate fusion strategy.
- **Multi-source candidates** contribute positively, confirming that signal agreement improves ranking quality.
- Basket-level context (e.g., `basket_size`) provides auxiliary but weaker signal.
- Category-based features play a supportive but secondary role.

---

### Conclusion

The Learning-to-Rank model successfully integrates heterogeneous candidate signals
and learns a coherent relevance function across baskets.

This confirms that:

- The candidate generation stage provides high-quality training signal
- Feature engineering choices are meaningful and interpretable
- The system is ready for further optimization and ablation analysis

In the next steps, we can:
- Perform detailed error analysis
- Compare against simpler baselines
- Tune hyperparameters
- Or prepare the model for production-style inference

## 3.2 Error Analysis and Failure Modes

In this section, we analyze **where and why the Learning-to-Rank model fails**
to retrieve the held-out item within the top-50 recommendations.

The goal is not to improve metrics directly, but to **understand model limitations**
and guide future improvements.

---

### Observed Validation Gap

- **Train Recall@50:** ~0.314  
- **Valid Recall@50:** ~0.217  

This gap suggests:
- Mild overfitting
- Distributional differences between training and validation baskets
- Sensitivity to sparse or weak-signal baskets

---

### Failure Pattern 1: Sparse Context Baskets

Baskets with:
- Very small `basket_size` (1–2 items)
- Limited historical co-occurrence
- Few or no rule-based signals

These baskets often produce:
- Single-source candidate pools
- Low multi-signal reinforcement
- Weaker ranking confidence

📉 Result: Held-out item is frequently ranked outside top-50.

---

### Failure Pattern 2: Embedding-Dominated Candidates

In some baskets:
- Most candidates originate from **embedding similarity**
- Rules and co-occurrence signals are absent or weak

While embeddings increase recall coverage, they introduce:
- Semantic noise
- Less precise intent matching

📉 Result: Correct item appears in pool but is ranked too low.

---

### Failure Pattern 3: Category-Only Signals

Candidates supported **only by category expansion** show:

- Low ranking stability
- Weak contribution to Recall@50
- Limited discrimination power

📉 Result: Category acts as a fallback signal, not a strong relevance driver.

---

### Failure Pattern 4: Signal Imbalance

Some baskets are dominated by:
- A single strong signal (e.g., rules only)
- Or many weak signals without agreement

📉 Result:
- Model over-trusts one signal
- Or fails to identify a clear relevance hierarchy

---

### What the Model Does Well

Despite these failures, the model performs strongly when:

- Candidates are supported by **multiple signals**
- Rule-based and co-occurrence signals are present
- Blended score and inverse-rank features align

📈 These cases dominate successful Recall@50 hits.

---

### Key Takeaways

- **Candidate quality still bounds ranking performance**
- Multi-source agreement is the strongest reliability indicator
- Sparse baskets remain the hardest problem
- Embeddings are useful but require gating or calibration

---

### Implications for Next Steps

Based on this analysis, promising improvements include:

- Context-aware signal gating
- Basket-size–dependent weighting
- Stronger regularization or early stopping
- Explicit handling of sparse baskets

This analysis informs the design of the next refinement stages.

## 3.3 Model and Signal Improvement Strategy

Based on the offline evaluation, ranking results, and error analysis,
this section outlines **concrete, evidence-driven improvement directions**
for the recommendation system.

The focus is not on immediate metric gains, but on **system robustness,
generalization, and production suitability**.

---

### 1. Context-Aware Signal Gating

Observations show that:
- Different baskets benefit from different signals
- Sparse baskets rely more on embeddings
- Dense baskets benefit strongly from rules and co-occurrence

**Proposed improvement:**
- Learn or heuristically define basket-aware signal weights
- Example:  
  - Small baskets → embedding-heavy  
  - Large baskets → rule / co-occurrence-heavy

This would reduce noise and improve ranking stability.

---

### 2. Explicit Handling of Sparse Baskets

Sparse baskets are the dominant failure mode.

Possible strategies:
- Separate ranking logic for basket_size ≤ 2
- Boost multi-source candidates when available
- Introduce popularity or recency priors as fallback

This avoids forcing the same ranking logic across fundamentally different contexts.

---

### 3. Stronger Regularization and Early Stopping

The observed train–validation gap suggests mild overfitting.

Improvements include:
- Stronger regularization on tree depth and leaf weights
- Early stopping based on validation NDCG
- Reduced model complexity for better generalization

---

### 4. Feature Refinements

Feature importance analysis indicates:
- Source indicators and blended scores dominate
- Category and basket size features contribute moderately

Potential refinements:
- Non-linear transformations of basket_size
- Normalized source agreement scores
- Interaction features between signal type and rank position

---

### 5. Candidate Quality as a First-Class Objective

Ranking performance is bounded by candidate quality.

Future iterations should:
- Optimize candidate generation recall explicitly
- Treat candidate generation and ranking as jointly optimized stages
- Monitor candidate-level Recall@K as a primary health metric

---

### Summary

Rather than adding model complexity, the most impactful improvements lie in:
- Smarter signal control
- Context-aware logic
- Better handling of edge cases

These changes prioritize **system reliability over isolated metric gains**,
which is essential for production-grade recommender systems.

## 3.4 Production Readiness and System Design

This section discusses how the proposed recommendation system would operate
in a **real-world production environment**, focusing on scalability,
latency, robustness, and maintainability.

The goal is to bridge the gap between an offline notebook experiment
and a deployable recommender system.

---

### 1. Offline–Online Separation

The system naturally decomposes into two layers:

**Offline (Batch) Layer**
- Association rules mining
- Co-occurrence statistics
- Item embeddings
- Category mappings
- Candidate generation diagnostics
- Learning-to-rank model training

These components are:
- Computed periodically (daily / weekly)
- Stored in fast-access data stores (feature store, key-value store)

**Online (Serving) Layer**
- Basket context ingestion
- Candidate retrieval from precomputed sources
- Lightweight feature assembly
- Ranking inference
- Top-K recommendation output

This separation ensures:
- Low latency at serving time
- Stable and reproducible behavior
- Easier debugging and monitoring

---

### 2. Latency and Fallback Strategy

To guarantee responsiveness under strict latency constraints:

- Candidate generation is capped (`top_k`)
- Ranking uses a single lightweight tree ensemble
- Feature computation avoids expensive joins

**Fallback logic:**
- If no candidates are generated → popularity-based fallback
- If ranking model fails → blended-score ordering
- If embeddings unavailable → rule and co-occurrence only

This ensures the system **never returns empty recommendations**.

---

### 3. Cold-Start Handling

Cold-start scenarios are addressed explicitly:

**New Items**
- Category-based candidates
- Popularity within category
- Gradual inclusion into co-occurrence statistics

**New Users / Sparse Baskets**
- Embedding-heavy candidate weighting
- Reduced reliance on rules
- Simple heuristic ranking as initial baseline

These strategies prevent early-stage degradation.

---

### 4. Monitoring and Health Metrics

In production, success is not measured by RMSE or R².

Key monitored metrics include:
- Candidate Recall@K
- Empty pool rate
- Average number of sources per candidate
- Source contribution distribution
- Latency percentiles (P50 / P95)

Alerts are triggered when:
- Candidate recall drops
- Multi-source agreement collapses
- Empty pools exceed threshold

---

### 5. Iterative Improvement Loop

The system is designed for continuous improvement:

1. Log served recommendations
2. Observe user interactions
3. Update candidate statistics
4. Retrain ranking model
5. Re-evaluate offline diagnostics

This creates a **closed feedback loop** between usage and learning.

---

### Summary

The proposed architecture emphasizes:
- Robustness over fragility
- Simplicity over unnecessary complexity
- Clear separation of concerns

As a result, the system is:
- Scalable
- Maintainable
- Production-ready

This completes the transition from experimental modeling
to a deployable recommender system.

## 4. Final Conclusions and Business Impact

This project demonstrates an end-to-end **basket-aware recommendation system**,
designed with real-world constraints in mind and evaluated through
industry-standard offline methodologies.

Rather than optimizing isolated models, the focus was on **system-level quality**.

---

### 4.1 What Was Built

We designed and validated a multi-stage recommender system consisting of:

- Multi-source candidate generation:
  - Association rules
  - Co-occurrence statistics
  - Item embeddings
  - Category-based expansion
- Robust candidate pooling and blending
- Offline diagnostics for candidate quality
- Learning-to-rank using a pairwise ranking objective
- Production-oriented evaluation metrics

Each component was tested independently and as part of the full pipeline.

---

### 4.2 Key Technical Outcomes

- Candidate generation achieved **strong Recall@50** before ranking
- Multi-source candidates consistently outperformed single-source signals
- Learning-to-rank improved ordering quality without increasing candidate size
- Feature importance analysis confirmed:
  - Rules and co-occurrence as strongest signals
  - Embeddings as complementary semantic context
- The system remained stable across:
  - Small baskets
  - Sparse contexts
  - Cold-start scenarios

These results validate both **model correctness** and **system robustness**.

---

### 4.3 Why RMSE Was Not Used

This project intentionally avoids regression metrics such as RMSE or R².

Reasons:
- The task is **ranking**, not value prediction
- User feedback is implicit and sparse
- Success is measured by *retrieval and ordering quality*

Instead, we relied on:
- Recall@K
- NDCG@K
- HitRate@K
- Source diversity diagnostics

These metrics align with how recommender systems are evaluated in production.

---

### 4.4 Business Impact

From a product perspective, the system enables:

- Higher basket expansion opportunities
- Increased cross-sell exposure
- Better personalization without heavy user profiling
- Reliable recommendations even under sparse data

From an engineering perspective:

- Low-latency serving
- Modular design
- Safe fallbacks
- Easy extensibility for new signals

This makes the system suitable for **large-scale e-commerce environments**.

---

### 4.5 Final Takeaway

The most important outcome of this project is not a single metric,
but a **repeatable, extensible recommendation framework**.

The system:

- Scales with data
- Improves with usage
- Degrades gracefully under uncertainty

This completes the transition from:
> *"building models"*  
to  
> *"engineering intelligent systems."*

## Production Export (Moved)

Rules ve pair artifact export işlemi notebooktan çıkarıldı.

Kullan:
```bash
python scripts/export_dashboard_artifacts.py
```

In [76]:
import sys, site
import mlxtend

print("python:", sys.executable)
print("mlxtend:", mlxtend.__version__)
print("site:", site.getsitepackages()[:2])

python: /Users/gizemtotkanli/.pyenv/versions/basket_ai/bin/python
mlxtend: 0.24.0
site: ['/Users/gizemtotkanli/.pyenv/versions/basket_ai/lib/python3.12/site-packages']